import { useState, useEffect, useRef, useCallback, useMemo } from "react";

// ═══════════════════════════════════════════════════════════════
// PRÉCIS — Full App UI (Mobile-First)
// All screens in one file. Backend-ready with mock data.
// ═══════════════════════════════════════════════════════════════

const THEMES={twilight:{id:"twilight",name:"Twilight Ink",icon:"☽",bg:"#111620",bg2:"#171D2A",bg3:"#1D2535",sf:"#151B28",bdr:"rgba(196,162,101,0.06)",bdrA:"rgba(196,162,101,0.16)",gold:"#C4A265",gs:"rgba(196,162,101,0.1)",acc:"#C06A30",as:"rgba(192,106,48,0.08)",tx:"#E4DED2",tx2:"#B8B0A2",tx3:"#7A7468",tx4:"#4E4A42",gn:"#6A9A60",rd:"#C45A4A",bl:"#5A8AB4",pl:"#9A70A0",tl:"#4EA8A0",hd:"'Cormorant Garamond',Georgia,serif",bd:"'Source Serif 4',Georgia,serif",ui:"'Outfit',system-ui,sans-serif",mn:"'JetBrains Mono',monospace",sh:"0 2px 8px rgba(0,0,0,.35)",shL:"0 8px 32px rgba(0,0,0,.45)"},parchment:{id:"parchment",name:"Warm Parchment",icon:"☀",bg:"#F4F0E6",bg2:"#ECE8DD",bg3:"#E2DDD1",sf:"#FFFDF5",bdr:"rgba(140,120,80,0.1)",bdrA:"rgba(140,120,80,0.24)",gold:"#A87A0A",gs:"rgba(168,122,10,0.07)",acc:"#B85A32",as:"rgba(184,90,50,0.06)",tx:"#2A2218",tx2:"#4A4030",tx3:"#8A7E6A",tx4:"#B8AD98",gn:"#5A7A4A",rd:"#A0422E",bl:"#4A6A8A",pl:"#7A5070",tl:"#3A8A7A",hd:"'Cormorant Garamond',Georgia,serif",bd:"'Source Serif 4',Georgia,serif",ui:"'Outfit',system-ui,sans-serif",mn:"'JetBrains Mono',monospace",sh:"0 1px 4px rgba(80,60,20,.05)",shL:"0 6px 24px rgba(80,60,20,.06)"},stone:{id:"stone",name:"Stone & Sage",icon:"◑",bg:"#E6E4DE",bg2:"#DCDAD2",bg3:"#D0CEC4",sf:"#F0EEE8",bdr:"rgba(100,96,82,0.1)",bdrA:"rgba(100,96,82,0.22)",gold:"#7A6E42",gs:"rgba(122,110,66,0.07)",acc:"#A85A3A",as:"rgba(168,90,58,0.06)",tx:"#28261E",tx2:"#44423A",tx3:"#78756C",tx4:"#A09C92",gn:"#4A7A56",rd:"#A0493A",bl:"#506A80",pl:"#7A5A6A",tl:"#3A8878",hd:"'Cormorant Garamond',Georgia,serif",bd:"'Source Serif 4',Georgia,serif",ui:"'Outfit',system-ui,sans-serif",mn:"'JetBrains Mono',monospace",sh:"0 1px 4px rgba(60,56,40,.05)",shL:"0 6px 24px rgba(60,56,40,.06)"},editorial:{id:"editorial",name:"Editorial",icon:"■",bg:"#F9F9F7",bg2:"#F0EFEC",bg3:"#E4E3DE",sf:"#FFFFFF",bdr:"rgba(0,0,0,0.05)",bdrA:"rgba(0,0,0,0.12)",gold:"#1A1A18",gs:"rgba(0,0,0,0.03)",acc:"#C44A20",as:"rgba(196,74,32,0.05)",tx:"#1A1A18",tx2:"#3A3A36",tx3:"#7A7A74",tx4:"#AAAAAA",gn:"#2A6A4A",rd:"#C44A20",bl:"#2A4A7A",pl:"#6A3A6A",tl:"#2A7A6A",hd:"'Cormorant Garamond',Georgia,serif",bd:"'Source Serif 4',Georgia,serif",ui:"'Outfit',system-ui,sans-serif",mn:"'JetBrains Mono',monospace",sh:"0 1px 3px rgba(0,0,0,.03)",shL:"0 4px 16px rgba(0,0,0,.04)"}};
function useTheme(){const[tid,setTid]=useState("twilight");return{T:THEMES[tid],tid,setTid};}

const TIERS=[{name:"Fresh Ink",min:0,c:"#8A8474"},{name:"Wet Ink",min:25,c:"#7AAAB8"},{name:"Set Ink",min:100,c:"#7AAA80"},{name:"Deep Ink",min:500,c:"#C4A265"},{name:"Indelible",min:2000,c:"#C06A30"}];
const gT=n=>{for(let i=TIERS.length-1;i>=0;i--)if(n>=TIERS[i].min)return TIERS[i];return TIERS[0];};
const fN=n=>n>=10000?(n/1000).toFixed(0)+"k":n>=1000?(n/1000).toFixed(1)+"k":String(n);
const LN={analyst:{icon:"🔬",label:"Analyst",c:"#5B9BD5"},empath:{icon:"💖",label:"Empath",c:"#D4788C"},philosopher:{icon:"💡",label:"Philosopher",c:"#D4A855"},storyteller:{icon:"🎭",label:"Storyteller",c:"#9B7ED4"},explorer:{icon:"🗺️",label:"Explorer",c:"#5BAD7A"},alchemist:{icon:"✧",label:"Alchemist",c:"#C4A06A"}};
const PT={original:{label:"Original",icon:"✎",ck:"acc"},review:{label:"Review",icon:"◈",ck:"gold"},recommendation:{label:"Rec",icon:"⬨",ck:"gn"},spoiler:{label:"Spoiler",icon:"⚠",ck:"rd"}};

// ─── DATA ────────────────────────────────────────────────────
const US=[{id:"u1",name:"Ingrid Solberg",h:"@ingridreads",in:"IS",ink:3420,lens:"analyst"},{id:"u2",name:"Kofi Asante",h:"@kofi_writes",in:"KA",ink:8750,lens:"storyteller"},{id:"u3",name:"Yuki Tanaka",h:"@yukiwrites",in:"YT",ink:1240,lens:"empath"},{id:"u4",name:"James Harlow",h:"@jharlow",in:"JH",ink:540,lens:"explorer"},{id:"u5",name:"Priya Anand",h:"@priyareads",in:"PA",ink:12300,lens:"empath"},{id:"u6",name:"Tomás Reyes",h:"@tomasreyes",in:"TR",ink:280,lens:"philosopher"},{id:"u7",name:"Aisha Keita",h:"@aishak",in:"AK",ink:4100,lens:"storyteller"},{id:"u8",name:"Amira Khoury",h:"@amirakhoury",in:"AM",ink:8400,lens:"alchemist"}];
const ME={id:"me",name:"Sean",h:"@sean",in:"SP",ink:1240,lens:"analyst",bio:"Structure is story.",posts:24,followers:142,following:89,booksRead:186};
const CR=[{user:US[0],book:"Intermezzo",author:"Sally Rooney",prog:72},{user:US[1],book:"James",author:"Percival Everett",prog:45},{user:US[4],book:"Orbital",author:"Samantha Harvey",prog:88},{user:US[2],book:"The Vegetarian",author:"Han Kang",prog:31},{user:US[6],book:"Creation Lake",author:"Rachel Kushner",prog:56}];
const FI=[{id:"p1",type:"review",user:US[0],time:"2h",bookRef:{title:"Intermezzo",author:"Sally Rooney",cc:"#3A5A4A"},title:"The architecture of longing",text:"Rooney builds Intermezzo like a fugue — two brothers, two registers, two ways of failing at intimacy. The formal innovation isn't the dual POV; it's how the prose style itself shifts between them.",rating:4,likes:47,comments:12,shelved:23,reposts:8,isLiked:false,isShelved:false,isReposted:false,tags:["literary-fiction","structure"],following:true,lensMatch:true},{id:"p2",type:"original",user:US[1],time:"4h",title:"Sixteen Funerals",text:"My grandmother attended sixteen funerals in the year she turned eighty. She told me once that grief has a sound — not the crying, not the hymns — but the moment after the last car leaves and the house goes quiet.\n\nI didn't understand until I heard it myself.",likes:89,comments:34,shelved:56,reposts:18,isLiked:true,isShelved:false,isReposted:false,tags:["flash-prose","grief"],following:true,isFirst:true,attestation:true},{id:"p3",type:"recommendation",user:US[4],time:"6h",bookRef:{title:"Orbital",author:"Samantha Harvey",cc:"#2A3A6A"},text:"If you've ever stared out a plane window and felt the weight of everyone below — read this. Harvey writes about astronauts the way mystics write about silence.",likes:112,comments:28,shelved:89,reposts:32,isLiked:false,isShelved:true,isReposted:false,tags:["literary-fiction"],following:true,lensMatch:true},{id:"p4",type:"spoiler",user:US[3],time:"8h",bookRef:{title:"James",author:"Percival Everett",cc:"#5A3A2A"},title:"The river scene rewrites everything",text:"When Jim's internal monologue drops the dialect for the first time — the real voice emerging — I physically set the book down.",spoilerPage:"p. 212",likes:34,comments:19,shelved:8,reposts:3,isLiked:false,isShelved:false,isReposted:false,tags:["historical-fiction"],lensMatch:true},{id:"p5",type:"original",user:US[7],time:"12h",title:"The Cartographer's Confession",text:"I have drawn borders where none exist. I have named rivers after men who never saw them. And in my seventy-third year, I understand that every map I made was a letter to someone I couldn't reach.\n\nMeasure it. Then forgive me for making it seem smaller than it was.",likes:203,comments:67,shelved:124,reposts:45,isLiked:false,isShelved:false,isReposted:false,tags:["poetry"],attestation:true,inspiredBy:{title:"Flights",author:"Olga Tokarczuk"}},{id:"p6",type:"review",user:US[2],time:"1d",bookRef:{title:"The Vegetarian",author:"Han Kang",cc:"#4A6A3A"},title:"Hunger as refusal",text:"Kang understands that the most terrifying act of autonomy isn't violence — it's silence.",rating:5,likes:78,comments:31,shelved:45,reposts:14,isLiked:false,isShelved:false,isReposted:false,tags:["international"],following:true}];
const TRD=[{title:"Intermezzo",author:"Sally Rooney",readers:412,heat:"+34%",c:"#3A5A4A"},{title:"James",author:"Percival Everett",readers:387,heat:"+28%",c:"#5A3A2A"},{title:"Orbital",author:"Samantha Harvey",readers:298,heat:"+22%",c:"#2A3A6A"},{title:"Beloved",author:"Toni Morrison",readers:342,heat:"+15%",c:"#6A2A3A"}];
const PRM=["Write about an object you inherited that carries more weight than it should.","The last lie your character told before everything changed.","A letter never sent, found decades later in a book.","Two strangers in a waiting room share the same recurring dream."];
const PRESS_WORKS=[{id:"w1",title:"The Cartographer's Confession",author:US[1],excerpt:"The first map I ever drew was a lie. I was nine, and my father had asked me to sketch the walk from our house to the schoolyard…",words:3200,form:"fiction",tags:["Literary Fiction","Magical Realism"],moods:["Haunting","Lush"],attested:true,likes:312,comments:87,shelved:94,readTime:13,featured:true,note:"A debut that reads like a myth being remembered.",lens:"storyteller"},{id:"w2",title:"Inheritance Tax",author:US[4],excerpt:"My grandmother left me her tongue. Not the language — I already had that, the Tamil she'd fed me like rice water when I was small…",words:1800,form:"essay",tags:["Memoir"],moods:["Tender","Elegiac"],attested:true,likes:489,comments:124,shelved:183,readTime:7,featured:true,note:"Inheritance as vocal cord, not document.",lens:"empath"},{id:"w3",title:"What the River Kept",author:{...US[2],name:"Amira Khalil"},excerpt:"I did not drown.\nThe river had its reasons\nfor releasing me —\n\nsomething about the way\nI held my breath\nlike a prayer I didn't believe in.",words:180,form:"poetry",tags:["Free Verse"],moods:["Quiet","Haunting"],attested:true,likes:267,comments:43,shelved:198,readTime:1,featured:true,note:"Every line break is a held breath.",lens:"empath"},{id:"w4",title:"Aubade for the Algorithm",author:{...US[5],name:"Nina Okafor",in:"NO",ink:2900},excerpt:"Good morning, machine.\nI have fed you my reading list,\nmy search history,\nthe 3 a.m. poems I wrote\nand deleted before the screen\ncould memorize my grief.",words:240,form:"poetry",tags:["Free Verse","Experimental"],moods:["Sharp","Playful"],attested:true,likes:567,comments:134,shelved:389,readTime:1,featured:true,note:"The best poem about AI is the most human one here.",lens:"philosopher"},{id:"w5",title:"On Rereading Beloved at Forty",author:{...US[3],name:"David Chen",in:"DC",ink:5600},excerpt:"The first time I read Beloved I was twenty-two and I thought it was about slavery. Now I am forty and I understand it is about the price of a self…",words:2100,form:"essay",tags:["Cultural Criticism","Craft / Writing"],moods:["Meditative","Warm"],attested:true,likes:178,comments:89,shelved:134,readTime:8,featured:false,lens:"philosopher"}];
const SHELF_ITEMS=[{id:"s1",type:"original",title:"What My Grandmother Left",authorName:"Priya Anand",lens:"empath",shelvedAt:"Feb 25",snippet:"My grandmother left me her tongue. Not the language — the physical fact of her voice…"},{id:"s2",type:"review",title:null,book:{title:"Beloved",author:"Toni Morrison"},authorName:"Marcus Cole",lens:"analyst",shelvedAt:"Feb 24",snippet:"Morrison doesn't write sentences. She builds rooms you don't realize you've entered until the door closes."},{id:"s3",type:"recommendation",title:null,book:{title:"The Vegetarian",author:"Han Kang"},authorName:"Yuki Tanaka",lens:"explorer",shelvedAt:"Feb 22",snippet:"If you read Kang's Nobel lecture and felt something shift beneath your feet, start here."},{id:"s4",type:"original",title:"Sixteen Deaths",authorName:"Priya Anand",lens:"empath",shelvedAt:"Feb 20",snippet:"My father has died sixteen times. The first was at SFO, 1987, when he forgot my name at the gate."}];
const MY_BOOKS=[{title:"Beloved",author:"Toni Morrison",status:"read",rating:5,genre:"Literary Fiction"},{title:"Intermezzo",author:"Sally Rooney",status:"reading",progress:72,genre:"Literary Fiction"},{title:"Orbital",author:"Samantha Harvey",status:"want",genre:"Literary Fiction"},{title:"The Vegetarian",author:"Han Kang",status:"read",rating:5,genre:"International"},{title:"James",author:"Percival Everett",status:"reading",progress:38,genre:"Historical Fiction"},{title:"Demon Copperhead",author:"Barbara Kingsolver",status:"want",genre:"Literary Fiction"}];
const CONVOS=[{id:"c1",user:US[0],lastMsg:"That Rooney review — I need to push back on the fugue metaphor…",time:"2h",unread:2},{id:"c2",user:US[4],lastMsg:"Did you see the new waypoint on Orbital? Page 180.",time:"5h",unread:0},{id:"c3",user:US[1],lastMsg:"Thank you for shelving Sixteen Funerals. That means a lot.",time:"1d",unread:0}];
const NOTIFS=[{id:"n1",actor:US[1],action:"commented on your review of",target:"Intermezzo",time:"20m",read:false},{id:"n2",actor:US[4],action:"shelved your post",target:"Inheritance Tax",time:"1h",read:false},{id:"n3",actor:US[0],action:"started following",target:"you",time:"3h",read:true},{id:"n4",actor:US[6],action:"liked your comment on",target:"The Cartographer's Confession",time:"5h",read:true},{id:"n5",actor:US[2],action:"mentioned you in a reply to",target:"Sixteen Funerals",time:"8h",read:true}];
const CLUBS=[{id:"cl1",name:"The Grief Shelf",book:"A Little Life",members:24,desc:"Books that sit with you after the last page.",active:true},{id:"cl2",name:"Prose as Architecture",book:"Absalom, Absalom!",members:18,desc:"When every sentence is load-bearing.",active:true},{id:"cl3",name:"Border Crossings",book:"Exit West",members:31,desc:"Literature that moves between worlds.",active:false}];
const CHALLENGES=[{id:"ch1",title:"March Deep Read",desc:"Read 4 books over 300 pages",progress:2,goal:4,reward:50,endsIn:"9 days",joined:true},{id:"ch2",title:"Around the World",desc:"Read books from 5 different countries",progress:3,goal:5,reward:75,endsIn:"18 days",joined:true},{id:"ch3",title:"Poetry Month Prep",desc:"Read 10 poems on The Press",progress:0,goal:10,reward:30,endsIn:"10 days",joined:false}];

// ─── CSS ─────────────────────────────────────────────────────
const gc=T=>`@import url('https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,400;0,500;0,600;0,700&family=Source+Serif+4:ital,opsz,wght@0,8..60,300;0,8..60,400;0,8..60,500;1,8..60,400&family=Outfit:wght@300;400;500;600;700;800&family=JetBrains+Mono:wght@400;500&display=swap');*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}body{background:${T.bg}!important;overflow-x:hidden;-webkit-tap-highlight-color:transparent}::selection{background:${T.gold}30;color:${T.tx}}::-webkit-scrollbar{width:0;height:0}@keyframes en{from{opacity:0;transform:translateY(6px)}to{opacity:1;transform:translateY(0)}}@keyframes fi{from{opacity:0}to{opacity:1}}@keyframes si{from{opacity:0;transform:scale(.97)}to{opacity:1;transform:scale(1)}}@keyframes po{0%{transform:scale(1)}50%{transform:scale(1.25)}100%{transform:scale(1)}}.tb{-webkit-tap-highlight-color:transparent;touch-action:manipulation}.tb:active{opacity:.7;transform:scale(.97)}.cl{transition:border-color .2s,box-shadow .15s}@media(min-width:768px){.mh{display:none!important}.dh{display:flex!important}.bb{display:none!important}.fw{padding-bottom:0!important;max-width:680px;margin:0 auto}.fs{display:grid!important;grid-template-columns:1fr 300px;gap:24px;max-width:1020px;margin:0 auto;align-items:start}.sd{display:flex!important}.cl:hover{border-color:${T.bdrA};box-shadow:${T.sh};transform:translateY(-1px)}}@media(max-width:767px){.dh{display:none!important}.sd{display:none!important}.fs{display:block!important}}`;

// ─── PRIMITIVES ──────────────────────────────────────────────
function Av({T,i,ink=0,s=34}){const t=gT(ink);return <div style={{width:s,height:s,borderRadius:"50%",background:`linear-gradient(145deg,${t.c}20,${T.bg2})`,border:`1.5px solid ${t.c}28`,display:"flex",alignItems:"center",justifyContent:"center",fontFamily:T.ui,fontSize:s*.34,fontWeight:700,color:t.c,flexShrink:0}}>{i}</div>;}
function IB({T,ink,compact}){const t=gT(ink);return <span style={{display:"inline-flex",alignItems:"center",gap:3,padding:compact?"1px 5px":"2px 7px",borderRadius:4,fontSize:compact?9:10,fontWeight:600,fontFamily:T.ui,color:t.c,background:`${t.c}0D`}}>{compact?fN(ink):`${fN(ink)} · ${t.name}`}</span>;}
function LB({T,lens,compact}){const l=LN[lens];if(!l)return null;return <span style={{display:"inline-flex",alignItems:"center",gap:2,padding:"1px 6px",borderRadius:4,fontSize:9,fontWeight:500,fontFamily:T.ui,color:l.c,background:`${l.c}08`}}>{l.icon}{!compact&&` ${l.label}`}</span>;}
function TT({T,type}){const t=PT[type];if(!t)return null;const c=T[t.ck]||T.gold;return <span style={{display:"inline-flex",alignItems:"center",gap:3,padding:"2px 8px",borderRadius:4,fontSize:9,fontWeight:700,fontFamily:T.ui,color:c,background:`${c}0D`,letterSpacing:".04em",textTransform:"uppercase"}}>{t.icon} {t.label}</span>;}
function EB({T,icon,count,active,ac,onClick}){const[p,sP]=useState(false);return <button className="tb" onClick={()=>{onClick?.();sP(true);setTimeout(()=>sP(false),300);}} style={{display:"flex",alignItems:"center",gap:4,padding:"8px 10px",borderRadius:8,background:active?`${ac}0D`:"transparent",border:"none",cursor:"pointer",animation:p?"po .3s ease":"none",minHeight:40}}><span style={{fontSize:15,color:active?ac:T.tx4}}>{icon}</span><span style={{fontFamily:T.ui,fontSize:11,fontWeight:600,color:active?ac:T.tx4,fontVariantNumeric:"tabular-nums"}}>{fN(count)}</span></button>;}
function Sec({T,title,sub,children,action}){return <section style={{marginBottom:24}}><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:10}}><div><div style={{fontFamily:T.hd,fontSize:17,fontWeight:600,color:T.tx}}>{title}</div>{sub&&<div style={{fontFamily:T.bd,fontSize:11,color:T.tx3,fontStyle:"italic",marginTop:1}}>{sub}</div>}</div>{action}</div>{children}</section>;}
function Card({T,children,pad="16px",mb=0}){return <div className="cl" style={{background:T.sf,borderRadius:14,border:`1px solid ${T.bdr}`,padding:pad,marginBottom:mb}}>{children}</div>;}
function Empty({T,icon,title,sub}){return <div style={{textAlign:"center",padding:"48px 16px",animation:"fi .3s ease"}}><div style={{fontSize:36,marginBottom:10,opacity:.15}}>{icon}</div><div style={{fontFamily:T.hd,fontSize:18,fontWeight:600,color:T.tx,marginBottom:6}}>{title}</div><p style={{fontFamily:T.bd,fontSize:13,color:T.tx3}}>{sub}</p></div>;}

// ─── FEED CARD ───────────────────────────────────────────────
function FC({T,item,onToggle,index=0}){const[so,setSo]=useState(false);const[mo,setMo]=useState(false);
const content=<>{item.title&&<h3 style={{fontFamily:T.hd,fontSize:19,fontWeight:600,color:T.tx,lineHeight:1.3,marginBottom:6}}>{item.title}</h3>}<div style={{fontFamily:T.bd,fontSize:14.5,lineHeight:1.7,color:T.tx2,fontWeight:300,whiteSpace:"pre-line"}}>{item.text}</div></>;
return <article className="cl" style={{background:T.sf,borderRadius:14,border:`1px solid ${T.bdr}`,padding:"18px 16px 12px",animation:`en .35s ease ${index*.05}s both`}}>
<div style={{display:"flex",alignItems:"flex-start",gap:10,marginBottom:12}}><Av T={T} i={item.user.in} ink={item.user.ink} s={38}/><div style={{flex:1,minWidth:0}}><div style={{display:"flex",alignItems:"center",gap:5,flexWrap:"wrap"}}><span style={{fontFamily:T.ui,fontSize:13.5,fontWeight:650,color:T.tx}}>{item.user.name}</span>{item.attestation&&<span style={{fontSize:8,padding:"1px 5px",borderRadius:3,background:`${T.gn}0D`,color:T.gn,fontFamily:T.ui,fontWeight:700}}>✓ HUMAN</span>}{item.isFirst&&<span style={{fontSize:8,padding:"1px 5px",borderRadius:3,background:`${T.gold}0D`,color:T.gold,fontFamily:T.ui,fontWeight:700}}>✦ FIRST</span>}</div><div style={{display:"flex",alignItems:"center",gap:5,marginTop:2,flexWrap:"wrap"}}><span style={{fontFamily:T.ui,fontSize:11,color:T.tx4}}>{item.user.h}</span><span style={{color:T.tx4,fontSize:8}}>·</span><span style={{fontFamily:T.ui,fontSize:11,color:T.tx4}}>{item.time}</span><IB T={T} ink={item.user.ink} compact/><LB T={T} lens={item.user.lens} compact/></div></div><div style={{display:"flex",alignItems:"center",gap:6,flexShrink:0}}><TT T={T} type={item.type}/><div style={{position:"relative"}}><button className="tb" onClick={()=>setMo(!mo)} style={{background:"none",border:"none",cursor:"pointer",padding:8,fontSize:18,color:T.tx4,minWidth:36,minHeight:36,display:"flex",alignItems:"center",justifyContent:"center"}}>⋮</button>{mo&&<div onClick={()=>setMo(false)} style={{position:"absolute",top:"100%",right:0,background:T.sf,border:`1px solid ${T.bdrA}`,borderRadius:12,padding:6,minWidth:160,boxShadow:T.shL,zIndex:50,animation:"si .12s ease"}}>{["Hide post","Mute author","Report"].map(a=><button key={a} className="tb" style={{display:"block",width:"100%",padding:"12px 14px",borderRadius:8,border:"none",background:"none",fontFamily:T.ui,fontSize:13,color:a==="Report"?T.rd:T.tx2,cursor:"pointer",textAlign:"left",minHeight:44}}>{a}</button>)}</div>}</div></div></div>
{item.bookRef&&<div style={{display:"flex",alignItems:"center",gap:10,padding:"8px 12px",borderRadius:8,background:T.bg2,border:`1px solid ${T.bdr}`,marginBottom:10}}><div style={{width:26,height:38,borderRadius:3,flexShrink:0,background:`linear-gradient(140deg,${item.bookRef.cc||T.acc}90,${item.bookRef.cc||T.acc}50)`}}/><div style={{flex:1,minWidth:0}}><div style={{fontFamily:T.ui,fontSize:12,fontWeight:600,color:T.tx}}>{item.bookRef.title}</div><div style={{fontFamily:T.ui,fontSize:10,color:T.tx3}}>{item.bookRef.author}</div></div>{item.rating&&<div style={{fontFamily:T.ui,fontSize:11,color:T.gold}}>{"★".repeat(item.rating)}<span style={{color:T.tx4}}>{"★".repeat(5-item.rating)}</span></div>}</div>}
{item.inspiredBy&&<div style={{display:"flex",alignItems:"center",gap:5,padding:"6px 10px",borderRadius:6,background:`${T.pl}06`,border:`1px solid ${T.pl}0D`,marginBottom:10,fontFamily:T.ui,fontSize:10.5,color:T.pl}}>◇ Inspired by <strong>{item.inspiredBy.title}</strong> — {item.inspiredBy.author}</div>}
{item.type==="spoiler"&&!so?<div style={{padding:"24px 16px",borderRadius:10,textAlign:"center",background:`repeating-linear-gradient(135deg,${T.rd}05,${T.rd}05 2px,transparent 2px,transparent 8px)`,border:`1px dashed ${T.rd}20`}}><div style={{fontFamily:T.ui,fontSize:10,fontWeight:700,color:T.rd,letterSpacing:".08em",textTransform:"uppercase",marginBottom:4}}>⚠ Spoiler Zone</div><div style={{fontFamily:T.bd,fontSize:12,color:T.tx3,marginBottom:14}}>{item.bookRef?.title}{item.spoilerPage?` · ${item.spoilerPage}`:""}</div><button className="tb" onClick={()=>setSo(true)} style={{padding:"10px 24px",borderRadius:8,background:`${T.rd}0D`,border:`1px solid ${T.rd}20`,fontFamily:T.ui,fontSize:12,fontWeight:600,color:T.rd,cursor:"pointer",minHeight:44}}>Reveal Content</button></div>:content}
{item.tags?.length>0&&<div style={{display:"flex",gap:4,flexWrap:"wrap",marginTop:10}}>{item.tags.map(t=><span key={t} style={{padding:"2px 8px",borderRadius:4,fontSize:10,fontFamily:T.ui,fontWeight:500,color:T.tx3,background:T.bg2,border:`1px solid ${T.bdr}`}}>{t}</span>)}</div>}
<div style={{display:"flex",alignItems:"center",gap:0,marginTop:12,paddingTop:10,borderTop:`1px solid ${T.bdr}`,marginLeft:-4,marginRight:-4}}><EB T={T} icon="♡" count={item.likes} active={item.isLiked} ac={T.rd} onClick={()=>onToggle(item.id,"like")}/><EB T={T} icon="↩" count={item.comments} active={false} ac={T.bl}/><EB T={T} icon="⊞" count={item.shelved} active={item.isShelved} ac={T.gold} onClick={()=>onToggle(item.id,"shelf")}/><EB T={T} icon="⤴" count={item.reposts} active={item.isReposted} ac={T.gn} onClick={()=>onToggle(item.id,"repost")}/><div style={{flex:1}}/><button className="tb" style={{background:"none",border:"none",cursor:"pointer",fontFamily:T.ui,fontSize:11,color:T.tx4,padding:"8px 6px",minHeight:40}}>⎘</button></div>
</article>;}

// ─── FEED SCREEN ─────────────────────────────────────────────
function FeedScreen({T,feed,onToggle,searchQ}){
const[filter,setFilter]=useState("foryou");const[pi,setPi]=useState(0);
const FL=[{id:"foryou",l:"✦ For You"},{id:"all",l:"All"},{id:"original",l:"✎ Original"},{id:"review",l:"◈ Reviews"},{id:"recommendation",l:"⬨ Recs"},{id:"spoiler",l:"⚠ Spoiler"}];
const filtered=filter==="foryou"?feed.filter(f=>f.following||f.lensMatch):filter==="all"?feed:feed.filter(f=>f.type===filter);
const searched=searchQ.trim()?filtered.filter(f=>{const q=searchQ.toLowerCase();return(f.title||"").toLowerCase().includes(q)||(f.text||"").toLowerCase().includes(q)||f.user.name.toLowerCase().includes(q)||(f.bookRef?.title||"").toLowerCase().includes(q);}):filtered;
return <>
<div style={{marginBottom:16}}><div style={{fontFamily:T.ui,fontSize:10,fontWeight:700,color:T.tx4,letterSpacing:".1em",textTransform:"uppercase",marginBottom:8}}>Currently Reading</div><div style={{display:"flex",gap:8,overflowX:"auto",WebkitOverflowScrolling:"touch",scrollSnapType:"x mandatory",scrollbarWidth:"none"}}>{CR.map((cr,i)=><div key={i} className="tb" style={{flex:"0 0 auto",scrollSnapAlign:"start",display:"flex",alignItems:"center",gap:10,padding:"10px 14px",borderRadius:12,background:T.sf,border:`1px solid ${T.bdr}`,minWidth:180,maxWidth:220}}><Av T={T} i={cr.user.in} ink={cr.user.ink} s={28}/><div style={{flex:1,minWidth:0}}><div style={{fontFamily:T.ui,fontSize:11.5,fontWeight:600,color:T.tx,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{cr.book}</div><div style={{fontFamily:T.ui,fontSize:10,color:T.tx4}}>{cr.author}</div></div><div style={{width:30,height:30,borderRadius:"50%",flexShrink:0,background:`conic-gradient(${T.acc} ${cr.prog}%,${T.bdr} ${cr.prog}%)`,display:"flex",alignItems:"center",justifyContent:"center"}}><div style={{width:24,height:24,borderRadius:"50%",background:T.sf,display:"flex",alignItems:"center",justifyContent:"center",fontFamily:T.mn,fontSize:8,fontWeight:500,color:T.tx3}}>{cr.prog}</div></div></div>)}</div></div>
<div style={{display:"flex",gap:6,overflowX:"auto",WebkitOverflowScrolling:"touch",marginBottom:14,scrollbarWidth:"none"}}>{FL.map(f=><button key={f.id} className="tb" onClick={()=>setFilter(f.id)} style={{padding:"8px 16px",borderRadius:20,border:`1px solid ${filter===f.id?T.bdrA:T.bdr}`,fontFamily:T.ui,fontSize:12,fontWeight:filter===f.id?700:500,cursor:"pointer",whiteSpace:"nowrap",minHeight:38,background:filter===f.id?T.gs:"transparent",color:filter===f.id?T.gold:T.tx3}}>{f.l}</button>)}</div>
{searchQ&&<div style={{fontFamily:T.ui,fontSize:12,color:T.tx3,marginBottom:12}}>⌕ "{searchQ}" · {searched.length} found</div>}
<Card T={T} pad="16px 16px 14px" mb={14}><div style={{fontFamily:T.ui,fontSize:9,fontWeight:700,color:T.acc,letterSpacing:".1em",textTransform:"uppercase",marginBottom:8}}>✎ Writing Prompt</div><div style={{fontFamily:T.hd,fontSize:16,fontWeight:500,color:T.tx,lineHeight:1.45,fontStyle:"italic",marginBottom:12}}>"{PRM[pi]}"</div><div style={{display:"flex",gap:8}}><button className="tb" style={{flex:1,padding:"10px 0",borderRadius:8,border:"none",background:T.acc,color:"#fff",fontFamily:T.ui,fontSize:12,fontWeight:700,cursor:"pointer",minHeight:44,boxShadow:`0 2px 8px ${T.acc}30`}}>Write This</button><button className="tb" onClick={()=>setPi((pi+1)%PRM.length)} style={{padding:"10px 18px",borderRadius:8,border:`1px solid ${T.bdr}`,background:"none",color:T.tx3,fontFamily:T.ui,fontSize:12,fontWeight:600,cursor:"pointer",minHeight:44}}>Next</button></div></Card>
<div style={{display:"flex",flexDirection:"column",gap:10}}>{searched.length===0?<Empty T={T} icon="⌕" title={searchQ?`Nothing for "${searchQ}"`:"No posts here yet"} sub={searchQ?"Try different keywords.":"Be the first to write one."}/>:searched.map((item,i)=><FC key={item.id} T={T} item={item} onToggle={onToggle} index={i}/>)}</div>
<div style={{marginTop:16}}><Card T={T} pad="16px 16px 8px"><div style={{fontFamily:T.hd,fontSize:16,fontWeight:600,color:T.tx,marginBottom:12}}>Trending Now</div>{TRD.map((b,i)=><div key={i} className="tb" style={{display:"flex",alignItems:"center",gap:10,padding:"10px 4px",cursor:"pointer",borderBottom:i<TRD.length-1?`1px solid ${T.bdr}`:"none",minHeight:48}}><div style={{fontFamily:T.mn,fontSize:11,fontWeight:500,color:T.tx4,width:18,textAlign:"center"}}>{i+1}</div><div style={{width:22,height:32,borderRadius:3,flexShrink:0,background:`linear-gradient(140deg,${b.c}AA,${b.c}60)`}}/><div style={{flex:1,minWidth:0}}><div style={{fontFamily:T.ui,fontSize:12,fontWeight:600,color:T.tx}}>{b.title}</div><div style={{fontFamily:T.ui,fontSize:10,color:T.tx3}}>{b.author}</div></div><span style={{fontFamily:T.mn,fontSize:10,fontWeight:500,color:T.gn,background:`${T.gn}0D`,padding:"2px 6px",borderRadius:3}}>{b.heat}</span></div>)}</Card></div>
{searched.length>0&&<div style={{textAlign:"center",padding:"40px 16px 24px",borderTop:`1px solid ${T.bdr}`,marginTop:16}}><div style={{fontFamily:T.hd,fontSize:20,fontWeight:600,color:T.tx,fontStyle:"italic",marginBottom:6}}>You're caught up.</div><p style={{fontFamily:T.bd,fontSize:13,color:T.tx3,lineHeight:1.6,maxWidth:340,margin:"0 auto 16px"}}>Everything new has been read. The page is yours.</p></div>}
</>;}

// ─── EXPLORE SCREEN ──────────────────────────────────────────
function ExploreScreen({T}){
const[following,setFl]=useState({});const[lf,setLf]=useState("all");
const readers=[...US].map((u,i)=>({...u,distance:["0.8 mi","1.2 mi","2.1 mi","3.4 mi","4.7 mi","6.2 mi","8.1 mi","12 mi"][i],currentBook:CR[i%CR.length]?.book||"Beloved",bio:["Reading as an act of feeling.","Structure is story.","Every sentence is a door.","What question does this book refuse to answer?","Borders are for crossing.","Prose should leave marks.","Language is the house of being.","Two threads. One needle."][i]}));
const filtered=lf==="all"?readers:readers.filter(u=>u.lens===lf);
return <div style={{animation:"en .35s ease both"}}>
<Sec T={T} title="📖 Reading Right Now" sub="Live"><div style={{display:"flex",gap:8,overflowX:"auto",WebkitOverflowScrolling:"touch",scrollbarWidth:"none"}}>{CR.slice(0,3).map((cr,i)=><Card key={i} T={T} pad="14px 16px"><div style={{display:"flex",alignItems:"center",gap:10}}><div style={{width:28,height:42,borderRadius:"1px 3px 3px 1px",background:`linear-gradient(145deg,${T.acc}CC,#6B2A10)`,boxShadow:"2px 0 6px rgba(0,0,0,.3)",flexShrink:0}}/><div><div style={{fontFamily:T.hd,fontSize:14,fontWeight:700,color:T.tx}}>{cr.book}</div><div style={{fontFamily:T.bd,fontSize:11,color:T.tx3,fontStyle:"italic"}}>{cr.author}</div></div></div></Card>)}</div></Sec>
<Sec T={T} title="📍 Readers Near You"><div style={{display:"flex",gap:5,overflowX:"auto",marginBottom:12,scrollbarWidth:"none"}}><button className="tb" onClick={()=>setLf("all")} style={{padding:"5px 12px",borderRadius:7,border:`1px solid ${lf==="all"?`${T.gold}25`:T.bdr}`,background:lf==="all"?T.gs:"transparent",fontFamily:T.ui,fontSize:10,fontWeight:lf==="all"?700:500,color:lf==="all"?T.gold:T.tx4,cursor:"pointer",whiteSpace:"nowrap"}}>All lenses</button>{Object.entries(LN).map(([k,v])=><button key={k} className="tb" onClick={()=>setLf(k)} style={{padding:"5px 12px",borderRadius:7,border:`1px solid ${lf===k?`${v.c}25`:T.bdr}`,background:lf===k?`${v.c}08`:"transparent",fontFamily:T.ui,fontSize:10,fontWeight:lf===k?700:500,color:lf===k?v.c:T.tx4,cursor:"pointer",whiteSpace:"nowrap"}}>{v.icon} {v.label}</button>)}</div>
<div style={{display:"flex",flexDirection:"column",gap:8}}>{filtered.map(u=>{const isF=following[u.id];return <Card key={u.id} T={T} pad="14px 16px"><div style={{display:"flex",alignItems:"center",gap:10}}><Av T={T} i={u.in} ink={u.ink} s={40}/><div style={{flex:1,minWidth:0}}><div style={{display:"flex",alignItems:"center",gap:5,flexWrap:"wrap"}}><span style={{fontFamily:T.ui,fontSize:12,fontWeight:700,color:T.tx}}>{u.name}</span><LB T={T} lens={u.lens} compact/><span style={{fontFamily:T.ui,fontSize:9,color:T.tx4}}>📍 {u.distance}</span></div><div style={{fontFamily:T.bd,fontSize:11,color:T.tx3,fontStyle:"italic",marginTop:1}}>{u.bio}</div><div style={{fontFamily:T.ui,fontSize:10,color:T.tx4,marginTop:4}}>Reading: <strong style={{color:T.tx2}}>{u.currentBook}</strong></div></div><button className="tb" onClick={()=>setFl(p=>({...p,[u.id]:!p[u.id]}))} style={{padding:"8px 14px",borderRadius:8,border:`1px solid ${isF?`${T.gn}25`:T.bdr}`,background:isF?`${T.gn}06`:"transparent",fontFamily:T.ui,fontSize:11,fontWeight:700,color:isF?T.gn:T.tx3,cursor:"pointer",flexShrink:0,minHeight:40}}>{isF?"✓ Following":"Follow"}</button></div></Card>})}</div></Sec>
<Sec T={T} title="🔥 Trending This Week"><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}>{TRD.map((b,i)=><Card key={i} T={T} pad="14px"><div style={{width:38,height:56,borderRadius:"1px 4px 4px 1px",background:`linear-gradient(145deg,${b.c}CC,${b.c}60)`,boxShadow:"2px 0 6px rgba(0,0,0,.3)",marginBottom:10}}/><div style={{fontFamily:T.hd,fontSize:13,fontWeight:700,color:T.tx,lineHeight:1.2,marginBottom:2}}>{b.title}</div><div style={{fontFamily:T.bd,fontSize:10,color:T.tx3,fontStyle:"italic",marginBottom:4}}>{b.author}</div><div style={{display:"flex",gap:6,fontFamily:T.ui,fontSize:9,color:T.tx4}}><span>{b.readers} readers</span><span style={{color:T.gn,fontWeight:700}}>{b.heat}</span></div></Card>)}</div></Sec>
</div>;}

// ─── PRESS SCREEN ────────────────────────────────────────────
function PressScreen({T}){
const[tab,setTab]=useState("discover");const[form,setForm]=useState("all");
const FF=[{id:"all",l:"All"},{id:"flash",l:"Flash"},{id:"fiction",l:"Fiction"},{id:"essay",l:"Essay"},{id:"poetry",l:"Poetry"}];
const filtered=form==="all"?PRESS_WORKS:form==="poetry"?PRESS_WORKS.filter(w=>w.form==="poetry"):form==="flash"?PRESS_WORKS.filter(w=>w.words<1000&&w.form!=="poetry"):PRESS_WORKS.filter(w=>w.form===form);
return <div style={{animation:"en .35s ease both"}}>
<div style={{marginBottom:16}}><h2 style={{fontFamily:T.hd,fontSize:24,fontWeight:700,color:T.tx,letterSpacing:"-.02em"}}>The Press</h2><p style={{fontFamily:T.bd,fontSize:12,color:T.tx3,fontStyle:"italic",marginTop:2}}>Original work — fiction, poetry, essays, and everything between.</p></div>
<div style={{display:"flex",gap:0,marginBottom:16,borderBottom:`1px solid ${T.bdr}`}}>{["discover","picks","trending"].map(t=><button key={t} className="tb" onClick={()=>setTab(t)} style={{padding:"10px 16px",border:"none",cursor:"pointer",fontFamily:T.ui,fontSize:12,fontWeight:tab===t?700:500,background:"transparent",color:tab===t?T.tx:T.tx3,borderBottom:tab===t?`2px solid ${T.acc}`:"2px solid transparent"}}>{t==="discover"?"Discover":t==="picks"?"Editor's Picks":"Trending"}</button>)}</div>
{tab==="discover"&&<><div style={{display:"flex",gap:3,marginBottom:14,overflowX:"auto",scrollbarWidth:"none"}}>{FF.map(f=><button key={f.id} className="tb" onClick={()=>setForm(f.id)} style={{padding:"6px 14px",borderRadius:8,border:`1px solid ${form===f.id?`${T.acc}20`:T.bdr}`,background:form===f.id?`${T.acc}0D`:"transparent",fontFamily:T.ui,fontSize:10,fontWeight:form===f.id?700:500,color:form===f.id?T.acc:T.tx3,cursor:"pointer",whiteSpace:"nowrap"}}>{f.l}</button>)}</div>
<div style={{display:"flex",flexDirection:"column",gap:12}}>{filtered.map(w=><Card key={w.id} T={T} pad="18px 16px"><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:10}}><Av T={T} i={w.author.in} ink={w.author.ink} s={32}/><div style={{flex:1}}><div style={{display:"flex",alignItems:"center",gap:5}}><span style={{fontFamily:T.ui,fontSize:12,fontWeight:700,color:T.tx}}>{w.author.name}</span><IB T={T} ink={w.author.ink} compact/></div><div style={{fontFamily:T.ui,fontSize:10,color:T.tx4}}>{w.readTime} min · {w.form}</div></div>{w.attested&&<span style={{fontSize:8,padding:"1px 5px",borderRadius:3,background:`${T.gn}0D`,color:T.gn,fontFamily:T.ui,fontWeight:700}}>✓ HUMAN</span>}</div>
<h3 style={{fontFamily:T.hd,fontSize:18,fontWeight:700,color:T.tx,fontStyle:"italic",lineHeight:1.3,marginBottom:8}}>{w.title}</h3>
{w.tags?.length>0&&<div style={{display:"flex",gap:3,flexWrap:"wrap",marginBottom:8}}>{w.tags.map(t=><span key={t} style={{padding:"2px 7px",borderRadius:4,fontSize:8,fontWeight:600,fontFamily:T.ui,background:`${T.acc}08`,color:T.acc}}>{t}</span>)}{w.moods?.map(t=><span key={t} style={{padding:"2px 7px",borderRadius:4,fontSize:8,fontFamily:T.ui,background:`${T.gold}06`,color:T.gold,fontStyle:"italic"}}>{t}</span>)}</div>}
<div style={{fontFamily:w.form==="poetry"?T.hd:T.bd,fontSize:w.form==="poetry"?14:13.5,lineHeight:w.form==="poetry"?1.9:1.7,color:T.tx2,fontWeight:w.form==="poetry"?400:300,whiteSpace:"pre-wrap",marginBottom:10}}>{w.excerpt.length>250?w.excerpt.slice(0,250)+"…":w.excerpt}</div>
{w.featured&&w.note&&<div style={{padding:"8px 12px",borderRadius:8,background:`${T.gold}04`,border:`1px solid ${T.gold}08`,marginBottom:8}}><div style={{fontFamily:T.bd,fontSize:10.5,color:T.gold,fontStyle:"italic"}}>🎨 {w.note}</div></div>}
<div style={{display:"flex",alignItems:"center",gap:10,fontFamily:T.ui,fontSize:10,color:T.tx4}}><span>{w.words.toLocaleString()} words</span><span style={{opacity:.3}}>·</span><span>♡ {w.likes}</span><span>💬 {w.comments}</span><span>◆ {w.shelved}</span></div></Card>)}</div></>}
{tab==="picks"&&<div style={{display:"flex",flexDirection:"column",gap:12}}><Card T={T} pad="16px"><div style={{fontFamily:T.hd,fontSize:16,fontWeight:700,color:T.gold,marginBottom:4}}>🎨 Editor's Picks</div><div style={{fontFamily:T.bd,fontSize:11,color:T.tx3,fontStyle:"italic",lineHeight:1.6}}>Work that embodies what Précis is for — writing that earns its place on the page.</div></Card>{PRESS_WORKS.filter(w=>w.featured).map(w=><Card key={w.id} T={T} pad="16px"><h3 style={{fontFamily:T.hd,fontSize:16,fontWeight:700,color:T.tx,fontStyle:"italic",marginBottom:4}}>{w.title}</h3><div style={{fontFamily:T.ui,fontSize:10,color:T.tx3,marginBottom:6}}>{w.author.name} · {w.form} · {w.readTime} min</div>{w.note&&<div style={{fontFamily:T.bd,fontSize:11,color:T.gold,fontStyle:"italic"}}>🎨 {w.note}</div>}</Card>)}</div>}
{tab==="trending"&&<div style={{display:"flex",flexDirection:"column",gap:10}}>{[...PRESS_WORKS].sort((a,b)=>(b.likes+b.shelved)-(a.likes+a.shelved)).map((w,i)=><div key={w.id} style={{display:"flex",alignItems:"flex-start",gap:10}}><div style={{fontFamily:T.hd,fontSize:22,fontWeight:700,color:`${T.gold}30`,width:28,textAlign:"right",flexShrink:0,marginTop:4}}>{i+1}</div><Card T={T} pad="14px 16px"><h3 style={{fontFamily:T.hd,fontSize:15,fontWeight:700,color:T.tx,fontStyle:"italic",marginBottom:2}}>{w.title}</h3><div style={{fontFamily:T.ui,fontSize:10,color:T.tx3}}>{w.author.name} · ♡ {w.likes} · ◆ {w.shelved}</div></Card></div>)}</div>}
</div>;}

// ─── COMPASS (Synopsis Engine) ───────────────────────────────
function CompassScreen({T}){
const[q,setQ]=useState("");const[mode,setMode]=useState("overview");const[result,setResult]=useState(null);
const BOOKS=[{title:"Beloved",author:"Toni Morrison"},{title:"Intermezzo",author:"Sally Rooney"},{title:"The Vegetarian",author:"Han Kang"},{title:"Orbital",author:"Samantha Harvey"},{title:"James",author:"Percival Everett"}];
const matches=q.trim()?BOOKS.filter(b=>b.title.toLowerCase().includes(q.toLowerCase())||b.author.toLowerCase().includes(q.toLowerCase())):[];
return <div style={{animation:"en .35s ease both"}}>
<Sec T={T} title="⌖ Compass" sub="AI-powered book analysis with Copyright Guard v1.2">
<Card T={T} pad="20px 16px"><div style={{fontFamily:T.ui,fontSize:10,fontWeight:700,color:T.tx4,letterSpacing:".08em",textTransform:"uppercase",marginBottom:10}}>Search a book to analyze</div>
<div style={{position:"relative",marginBottom:12}}><input value={q} onChange={e=>{setQ(e.target.value);setResult(null);}} placeholder="Search by title or author…" style={{width:"100%",padding:"12px 14px 12px 36px",borderRadius:10,background:T.bg2,border:`1px solid ${q?T.bdrA:T.bdr}`,fontFamily:T.ui,fontSize:13,color:T.tx,outline:"none"}}/><span style={{position:"absolute",left:12,top:"50%",transform:"translateY(-50%)",fontSize:14,color:T.tx4,pointerEvents:"none"}}>⌕</span></div>
{matches.length>0&&!result&&<div style={{display:"flex",flexDirection:"column",gap:4,marginBottom:12}}>{matches.map(b=><button key={b.title} className="tb" onClick={()=>{setResult(b);setQ(b.title);}} style={{display:"flex",alignItems:"center",gap:10,padding:"10px 12px",borderRadius:8,border:`1px solid ${T.bdr}`,background:"transparent",cursor:"pointer",minHeight:44,textAlign:"left",width:"100%"}}><div style={{width:22,height:32,borderRadius:3,background:`linear-gradient(140deg,${T.acc}90,${T.acc}50)`,flexShrink:0}}/><div><div style={{fontFamily:T.ui,fontSize:12,fontWeight:600,color:T.tx}}>{b.title}</div><div style={{fontFamily:T.ui,fontSize:10,color:T.tx3}}>{b.author}</div></div></button>)}</div>}
{result&&<><div style={{display:"flex",gap:4,marginBottom:14,overflowX:"auto",scrollbarWidth:"none"}}>{["overview","themes","characters","structure","quotes","compare"].map(m=><button key={m} className="tb" onClick={()=>setMode(m)} style={{padding:"7px 14px",borderRadius:8,border:`1px solid ${mode===m?T.bdrA:T.bdr}`,background:mode===m?T.gs:"transparent",fontFamily:T.ui,fontSize:10,fontWeight:mode===m?700:500,color:mode===m?T.gold:T.tx3,cursor:"pointer",whiteSpace:"nowrap",textTransform:"capitalize"}}>{m}</button>)}</div>
<Card T={T} pad="16px"><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:14}}><div style={{width:32,height:48,borderRadius:3,background:`linear-gradient(145deg,${T.acc}CC,#6B2A10)`,boxShadow:"2px 0 6px rgba(0,0,0,.3)",flexShrink:0}}/><div><div style={{fontFamily:T.hd,fontSize:18,fontWeight:700,color:T.tx}}>{result.title}</div><div style={{fontFamily:T.bd,fontSize:12,color:T.tx3,fontStyle:"italic"}}>{result.author}</div></div></div>
<div style={{padding:"16px",borderRadius:10,background:`${T.gold}04`,border:`1px solid ${T.gold}08`}}><div style={{fontFamily:T.ui,fontSize:9,fontWeight:700,color:T.gold,letterSpacing:".08em",textTransform:"uppercase",marginBottom:8}}>⌖ {mode} Analysis</div><div style={{fontFamily:T.bd,fontSize:13,lineHeight:1.7,color:T.tx2,fontWeight:300}}>This analysis would be generated by the Synopsis Engine via Claude Sonnet 4.6 with Copyright Guard v1.2. The engine provides 6 analytical lenses, 3 output formats, and fiction/nonfiction detection.</div><div style={{fontFamily:T.ui,fontSize:10,color:T.tx4,marginTop:10,display:"flex",alignItems:"center",gap:6}}>🔒 Copyright Guard active · Estimated cost: ~$0.02</div></div></Card></>}
</Card></Sec></div>;}

// ─── SHELF SCREEN ────────────────────────────────────────────
function ShelfScreen({T}){
const[tab,setTab]=useState("shelved");const[bookFilter,setBf]=useState("all");
const BF=[{id:"all",l:"All"},{id:"reading",l:"📖 Reading"},{id:"read",l:"✓ Read"},{id:"want",l:"◇ Want"}];
const filteredBooks=bookFilter==="all"?MY_BOOKS:MY_BOOKS.filter(b=>b.status===bookFilter);
return <div style={{animation:"en .35s ease both"}}>
<div style={{marginBottom:16}}><h2 style={{fontFamily:T.hd,fontSize:22,fontWeight:700,color:T.tx}}>My Shelf</h2><div style={{display:"flex",gap:12,marginTop:6,fontFamily:T.ui,fontSize:11,color:T.tx3}}><span>{MY_BOOKS.length} books</span><span>·</span><span>{SHELF_ITEMS.length} shelved posts</span></div></div>
<div style={{display:"flex",gap:0,marginBottom:16,borderBottom:`1px solid ${T.bdr}`}}>{[{id:"shelved",l:"Shelved Posts"},{id:"library",l:"Library"},{id:"waypoints",l:"Waypoints"}].map(t=><button key={t.id} className="tb" onClick={()=>setTab(t.id)} style={{padding:"10px 16px",border:"none",cursor:"pointer",fontFamily:T.ui,fontSize:12,fontWeight:tab===t.id?700:500,background:"transparent",color:tab===t.id?T.tx:T.tx3,borderBottom:tab===t.id?`2px solid ${T.acc}`:"2px solid transparent"}}>{t.l}</button>)}</div>
{tab==="shelved"&&<div style={{display:"flex",flexDirection:"column",gap:8}}>{SHELF_ITEMS.map(s=><Card key={s.id} T={T} pad="14px 16px"><div style={{display:"flex",alignItems:"center",gap:6,marginBottom:6}}><TT T={T} type={s.type}/><span style={{fontFamily:T.ui,fontSize:10,color:T.tx4}}>Shelved {s.shelvedAt}</span></div>{s.title&&<div style={{fontFamily:T.hd,fontSize:15,fontWeight:600,color:T.tx,marginBottom:4}}>{s.title}</div>}{s.book&&<div style={{fontFamily:T.ui,fontSize:11,color:T.tx2,marginBottom:4}}>on <strong>{s.book.title}</strong> by {s.book.author}</div>}<div style={{fontFamily:T.bd,fontSize:12.5,lineHeight:1.6,color:T.tx3,fontWeight:300}}>{s.snippet}</div><div style={{fontFamily:T.ui,fontSize:10,color:T.tx4,marginTop:6}}>by {s.authorName} · <LB T={T} lens={s.lens} compact/></div></Card>)}</div>}
{tab==="library"&&<><div style={{display:"flex",gap:6,marginBottom:14,overflowX:"auto",scrollbarWidth:"none"}}>{BF.map(f=><button key={f.id} className="tb" onClick={()=>setBf(f.id)} style={{padding:"7px 14px",borderRadius:20,border:`1px solid ${bookFilter===f.id?T.bdrA:T.bdr}`,background:bookFilter===f.id?T.gs:"transparent",fontFamily:T.ui,fontSize:11,fontWeight:bookFilter===f.id?700:500,color:bookFilter===f.id?T.gold:T.tx3,cursor:"pointer",whiteSpace:"nowrap"}}>{f.l}</button>)}</div>
<div style={{display:"flex",flexDirection:"column",gap:8}}>{filteredBooks.map((b,i)=><Card key={i} T={T} pad="14px 16px"><div style={{display:"flex",alignItems:"center",gap:10}}><div style={{width:28,height:42,borderRadius:3,background:`linear-gradient(145deg,${T.acc}CC,#6B2A10)`,boxShadow:"2px 0 6px rgba(0,0,0,.25)",flexShrink:0}}/><div style={{flex:1}}><div style={{fontFamily:T.hd,fontSize:14,fontWeight:700,color:T.tx}}>{b.title}</div><div style={{fontFamily:T.bd,fontSize:11,color:T.tx3,fontStyle:"italic"}}>{b.author}</div><div style={{display:"flex",alignItems:"center",gap:6,marginTop:3}}><span style={{fontFamily:T.ui,fontSize:9,padding:"2px 6px",borderRadius:4,background:b.status==="reading"?`${T.bl}0D`:b.status==="read"?`${T.gn}0D`:`${T.gold}0D`,color:b.status==="reading"?T.bl:b.status==="read"?T.gn:T.gold,fontWeight:600}}>{b.status==="reading"?"📖 Reading":b.status==="read"?"✓ Read":"◇ Want"}</span>{b.rating&&<span style={{fontFamily:T.ui,fontSize:10,color:T.gold}}>{"★".repeat(b.rating)}</span>}{b.progress&&<span style={{fontFamily:T.mn,fontSize:9,color:T.acc}}>{b.progress}%</span>}</div></div></div></Card>)}</div></>}
{tab==="waypoints"&&<Empty T={T} icon="⟐" title="No waypoints yet" sub="Waypoints are reading reflections tied to specific page numbers. Start one from any book detail page."/>}
</div>;}

// ─── PROFILE ─────────────────────────────────────────────────
function ProfileScreen({T}){
const[tab,setTab]=useState("posts");const tier=gT(ME.ink);const lens=LN[ME.lens];
return <div style={{animation:"en .35s ease both"}}>
<Card T={T} pad="24px 16px" mb={16}><div style={{display:"flex",alignItems:"center",gap:14,marginBottom:16}}><Av T={T} i={ME.in} ink={ME.ink} s={56}/><div style={{flex:1}}><div style={{fontFamily:T.hd,fontSize:22,fontWeight:700,color:T.tx}}>{ME.name}</div><div style={{fontFamily:T.ui,fontSize:12,color:T.tx4,marginTop:2}}>{ME.h}</div><div style={{display:"flex",gap:6,marginTop:6}}><IB T={T} ink={ME.ink}/><LB T={T} lens={ME.lens}/></div></div><button className="tb" style={{padding:"8px 16px",borderRadius:8,border:`1px solid ${T.bdr}`,background:"transparent",fontFamily:T.ui,fontSize:11,fontWeight:600,color:T.tx3,cursor:"pointer",minHeight:40}}>Edit</button></div>
<div style={{fontFamily:T.bd,fontSize:13,color:T.tx2,fontStyle:"italic",lineHeight:1.6,marginBottom:16}}>{ME.bio}</div>
<div style={{display:"flex",gap:20,fontFamily:T.ui,fontSize:12}}><div><strong style={{color:T.tx,fontSize:16}}>{ME.posts}</strong><div style={{color:T.tx4,fontSize:10}}>Posts</div></div><div><strong style={{color:T.tx,fontSize:16}}>{ME.followers}</strong><div style={{color:T.tx4,fontSize:10}}>Followers</div></div><div><strong style={{color:T.tx,fontSize:16}}>{ME.following}</strong><div style={{color:T.tx4,fontSize:10}}>Following</div></div><div><strong style={{color:T.tx,fontSize:16}}>{ME.booksRead}</strong><div style={{color:T.tx4,fontSize:10}}>Books Read</div></div></div>
<div style={{marginTop:16,padding:"12px 14px",borderRadius:10,background:`${tier.c}08`,border:`1px solid ${tier.c}15`}}><div style={{display:"flex",alignItems:"center",justifyContent:"space-between"}}><div><div style={{fontFamily:T.ui,fontSize:10,fontWeight:700,color:tier.c,letterSpacing:".06em",textTransform:"uppercase"}}>{tier.name}</div><div style={{fontFamily:T.mn,fontSize:20,fontWeight:700,color:tier.c}}>{fN(ME.ink)}</div></div><div style={{width:80,height:4,borderRadius:2,background:`${tier.c}15`}}><div style={{width:`${Math.min((ME.ink/(TIERS[TIERS.findIndex(t=>t===tier)+1]?.min||2000))*100,100)}%`,height:"100%",borderRadius:2,background:tier.c}}/></div></div></div></Card>
<div style={{display:"flex",gap:0,marginBottom:14,borderBottom:`1px solid ${T.bdr}`}}>{[{id:"posts",l:"Posts"},{id:"shelves",l:"Shelves"},{id:"about",l:"About"}].map(t=><button key={t.id} className="tb" onClick={()=>setTab(t.id)} style={{padding:"10px 16px",border:"none",cursor:"pointer",fontFamily:T.ui,fontSize:12,fontWeight:tab===t.id?700:500,background:"transparent",color:tab===t.id?T.tx:T.tx3,borderBottom:tab===t.id?`2px solid ${T.acc}`:"2px solid transparent"}}>{t.l}</button>)}</div>
{tab==="posts"&&<div style={{display:"flex",flexDirection:"column",gap:10}}>{FI.filter(f=>f.user.id==="u1").length===0?<Empty T={T} icon="✎" title="No posts yet" sub="Your first post earns +10 Ink."/>:FI.slice(0,2).map((item,i)=><Card key={item.id} T={T} pad="14px 16px"><div style={{fontFamily:T.hd,fontSize:15,fontWeight:600,color:T.tx,marginBottom:4}}>{item.title||item.bookRef?.title}</div><div style={{fontFamily:T.bd,fontSize:12,color:T.tx3,lineHeight:1.5}}>{item.text.slice(0,120)}…</div><div style={{fontFamily:T.ui,fontSize:10,color:T.tx4,marginTop:6}}>♡ {item.likes} · 💬 {item.comments} · ◆ {item.shelved}</div></Card>)}</div>}
{tab==="shelves"&&<div style={{display:"flex",flexDirection:"column",gap:8}}>{SHELF_ITEMS.slice(0,3).map(s=><Card key={s.id} T={T} pad="12px 14px"><div style={{fontFamily:T.hd,fontSize:14,fontWeight:600,color:T.tx}}>{s.title||s.book?.title}</div><div style={{fontFamily:T.ui,fontSize:10,color:T.tx4,marginTop:2}}>by {s.authorName} · Shelved {s.shelvedAt}</div></Card>)}</div>}
{tab==="about"&&<Card T={T} pad="16px"><div style={{fontFamily:T.ui,fontSize:10,fontWeight:700,color:T.tx4,letterSpacing:".08em",textTransform:"uppercase",marginBottom:10}}>Reader Identity</div><div style={{display:"flex",gap:8,flexWrap:"wrap",marginBottom:16}}><IB T={T} ink={ME.ink}/><LB T={T} lens={ME.lens}/></div><div style={{fontFamily:T.ui,fontSize:10,fontWeight:700,color:T.tx4,letterSpacing:".08em",textTransform:"uppercase",marginBottom:8}}>Reading Stats</div><div style={{fontFamily:T.bd,fontSize:13,color:T.tx2,lineHeight:1.8}}>{ME.booksRead} books read · Member since Jan 2026</div></Card>}
</div>;}

// ─── MESSAGES ────────────────────────────────────────────────
function MessagesScreen({T}){
const[active,setActive]=useState(null);
if(active){const c=CONVOS.find(x=>x.id===active);return <div style={{animation:"en .3s ease both"}}><button className="tb" onClick={()=>setActive(null)} style={{fontFamily:T.ui,fontSize:12,color:T.tx3,background:"none",border:"none",cursor:"pointer",marginBottom:14,minHeight:40}}>← Back</button><Card T={T} pad="16px"><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:16,paddingBottom:12,borderBottom:`1px solid ${T.bdr}`}}><Av T={T} i={c.user.in} ink={c.user.ink} s={36}/><div><div style={{fontFamily:T.ui,fontSize:13,fontWeight:700,color:T.tx}}>{c.user.name}</div><IB T={T} ink={c.user.ink} compact/></div></div>
<div style={{minHeight:200,display:"flex",flexDirection:"column",justifyContent:"flex-end",gap:8,marginBottom:16}}>
<div style={{alignSelf:"flex-start",maxWidth:"80%",padding:"10px 14px",borderRadius:"14px 14px 14px 4px",background:T.bg2}}><div style={{fontFamily:T.bd,fontSize:13,color:T.tx2,lineHeight:1.5}}>{c.lastMsg}</div><div style={{fontFamily:T.ui,fontSize:9,color:T.tx4,marginTop:4}}>{c.time} ago</div></div>
<div style={{alignSelf:"flex-end",maxWidth:"80%",padding:"10px 14px",borderRadius:"14px 14px 4px 14px",background:`${T.acc}15`}}><div style={{fontFamily:T.bd,fontSize:13,color:T.tx,lineHeight:1.5}}>I'll take a closer look at that section tonight.</div><div style={{fontFamily:T.ui,fontSize:9,color:T.tx4,marginTop:4}}>Just now</div></div></div>
<div style={{display:"flex",gap:8}}><input placeholder="Write a message…" style={{flex:1,padding:"12px 14px",borderRadius:10,background:T.bg2,border:`1px solid ${T.bdr}`,fontFamily:T.ui,fontSize:13,color:T.tx,outline:"none"}}/><button className="tb" style={{padding:"10px 18px",borderRadius:10,border:"none",background:T.acc,color:"#fff",fontFamily:T.ui,fontSize:12,fontWeight:700,cursor:"pointer",minHeight:44}}>Send</button></div></Card></div>;}
return <div style={{animation:"en .35s ease both"}}><Sec T={T} title="Messages"><div style={{display:"flex",flexDirection:"column",gap:8}}>{CONVOS.map(c=><button key={c.id} className="tb" onClick={()=>setActive(c.id)} style={{display:"flex",alignItems:"center",gap:10,padding:"14px 16px",borderRadius:14,background:T.sf,border:`1px solid ${c.unread?T.bdrA:T.bdr}`,cursor:"pointer",width:"100%",textAlign:"left",minHeight:60}}><div style={{position:"relative"}}><Av T={T} i={c.user.in} ink={c.user.ink} s={40}/>{c.unread>0&&<div style={{position:"absolute",top:-2,right:-2,width:16,height:16,borderRadius:"50%",background:T.acc,fontFamily:T.ui,fontSize:9,fontWeight:700,color:"#fff",display:"flex",alignItems:"center",justifyContent:"center"}}>{c.unread}</div>}</div><div style={{flex:1,minWidth:0}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:2}}><span style={{fontFamily:T.ui,fontSize:13,fontWeight:c.unread?700:600,color:T.tx}}>{c.user.name}</span><span style={{fontFamily:T.ui,fontSize:10,color:T.tx4}}>{c.time}</span></div><div style={{fontFamily:T.bd,fontSize:12,color:c.unread?T.tx2:T.tx3,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{c.lastMsg}</div></div></button>)}</div></Sec></div>;}

// ─── NOTIFICATIONS ───────────────────────────────────────────
function NotifsScreen({T}){return <div style={{animation:"en .35s ease both"}}><Sec T={T} title="Notifications"><div style={{display:"flex",flexDirection:"column",gap:4}}>{NOTIFS.map(n=><div key={n.id} style={{display:"flex",alignItems:"center",gap:10,padding:"12px 14px",borderRadius:10,background:n.read?"transparent":`${T.acc}04`,border:`1px solid ${n.read?T.bdr:T.bdrA}`}}><Av T={T} i={n.actor.in} ink={n.actor.ink} s={34}/><div style={{flex:1}}><div style={{fontFamily:T.ui,fontSize:12,color:T.tx2,lineHeight:1.5}}><strong style={{color:T.tx,fontWeight:700}}>{n.actor.name}</strong> {n.action} <strong style={{color:T.tx}}>{n.target}</strong></div><div style={{fontFamily:T.ui,fontSize:10,color:T.tx4,marginTop:2}}>{n.time} ago</div></div>{!n.read&&<div style={{width:8,height:8,borderRadius:"50%",background:T.acc,flexShrink:0}}/>}</div>)}</div></Sec></div>;}

// ─── BOOK CLUBS ──────────────────────────────────────────────
function ClubsScreen({T}){return <div style={{animation:"en .35s ease both"}}><Sec T={T} title="Book Clubs" action={<button className="tb" style={{padding:"8px 14px",borderRadius:8,border:"none",background:T.acc,color:"#fff",fontFamily:T.ui,fontSize:11,fontWeight:700,cursor:"pointer",minHeight:36}}>+ Create</button>}><div style={{display:"flex",flexDirection:"column",gap:10}}>{CLUBS.map(c=><Card key={c.id} T={T} pad="16px"><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start"}}><div><div style={{fontFamily:T.hd,fontSize:16,fontWeight:700,color:T.tx,marginBottom:2}}>{c.name}</div><div style={{fontFamily:T.bd,fontSize:12,color:T.tx3,fontStyle:"italic",lineHeight:1.5,marginBottom:6}}>{c.desc}</div><div style={{display:"flex",gap:8,fontFamily:T.ui,fontSize:10,color:T.tx4}}><span>📖 {c.book}</span><span>·</span><span>{c.members} members</span></div></div>{c.active?<span style={{padding:"4px 10px",borderRadius:6,fontFamily:T.ui,fontSize:9,fontWeight:700,color:T.gn,background:`${T.gn}0D`}}>Active</span>:<span style={{padding:"4px 10px",borderRadius:6,fontFamily:T.ui,fontSize:9,fontWeight:600,color:T.tx4,background:`${T.tx4}08`}}>Completed</span>}</div></Card>)}</div></Sec></div>;}

// ─── CHALLENGES ──────────────────────────────────────────────
function ChallengesScreen({T}){return <div style={{animation:"en .35s ease both"}}><Sec T={T} title="Challenges" sub="Reading goals with Ink rewards"><div style={{display:"flex",flexDirection:"column",gap:10}}>{CHALLENGES.map(ch=><Card key={ch.id} T={T} pad="16px"><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:10}}><div><div style={{fontFamily:T.hd,fontSize:16,fontWeight:700,color:T.tx,marginBottom:2}}>{ch.title}</div><div style={{fontFamily:T.bd,fontSize:12,color:T.tx3,lineHeight:1.5}}>{ch.desc}</div></div><span style={{fontFamily:T.ui,fontSize:10,fontWeight:700,color:T.gold,background:`${T.gold}0D`,padding:"3px 8px",borderRadius:4,flexShrink:0}}>+{ch.reward} Ink</span></div>
<div style={{display:"flex",alignItems:"center",gap:10,marginBottom:8}}><div style={{flex:1,height:6,borderRadius:3,background:`${T.gold}10`}}><div style={{width:`${(ch.progress/ch.goal)*100}%`,height:"100%",borderRadius:3,background:`linear-gradient(90deg,${T.acc},${T.gold})`}}/></div><span style={{fontFamily:T.mn,fontSize:11,fontWeight:600,color:T.tx2}}>{ch.progress}/{ch.goal}</span></div>
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><span style={{fontFamily:T.ui,fontSize:10,color:T.tx4}}>Ends in {ch.endsIn}</span>{ch.joined?<span style={{fontFamily:T.ui,fontSize:10,fontWeight:700,color:T.gn}}>✓ Joined</span>:<button className="tb" style={{padding:"7px 14px",borderRadius:8,border:"none",background:T.acc,color:"#fff",fontFamily:T.ui,fontSize:11,fontWeight:700,cursor:"pointer",minHeight:36}}>Join</button>}</div></Card>)}</div></Sec></div>;}

// ─── SETTINGS ────────────────────────────────────────────────
function SettingsScreen({T,tid,setTid}){
const[notifs,setN]=useState({likes:true,comments:true,follows:true,clubs:true,challenges:true});
const[priv,setP]=useState({showReading:true,showLocation:false,publicProfile:true});
function Tog({on,onToggle,label}){return <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"12px 0",borderBottom:`1px solid ${T.bdr}`}}><span style={{fontFamily:T.ui,fontSize:13,color:T.tx}}>{label}</span><button className="tb" onClick={onToggle} style={{width:44,height:26,borderRadius:13,background:on?T.acc:`${T.tx4}30`,border:"none",cursor:"pointer",position:"relative",transition:"background .2s"}}><div style={{width:20,height:20,borderRadius:"50%",background:"#fff",position:"absolute",top:3,left:on?21:3,transition:"left .2s",boxShadow:"0 1px 3px rgba(0,0,0,.2)"}}/></button></div>;}
return <div style={{animation:"en .35s ease both"}}>
<Sec T={T} title="Settings">
<Card T={T} pad="16px" mb={14}><div style={{fontFamily:T.ui,fontSize:10,fontWeight:700,color:T.tx4,letterSpacing:".08em",textTransform:"uppercase",marginBottom:8}}>Account</div><div style={{display:"flex",alignItems:"center",gap:10,padding:"12px 0",borderBottom:`1px solid ${T.bdr}`}}><Av T={T} i={ME.in} ink={ME.ink} s={40}/><div style={{flex:1}}><div style={{fontFamily:T.ui,fontSize:13,fontWeight:600,color:T.tx}}>{ME.name}</div><div style={{fontFamily:T.ui,fontSize:11,color:T.tx4}}>{ME.h}</div></div><button className="tb" style={{fontFamily:T.ui,fontSize:11,color:T.acc,background:"none",border:"none",cursor:"pointer"}}>Edit</button></div></Card>
<Card T={T} pad="16px" mb={14}><div style={{fontFamily:T.ui,fontSize:10,fontWeight:700,color:T.tx4,letterSpacing:".08em",textTransform:"uppercase",marginBottom:8}}>Theme</div><div style={{display:"flex",gap:6,flexWrap:"wrap"}}>{Object.values(THEMES).map(t=>{const a=t.id===tid;return <button key={t.id} className="tb" onClick={()=>setTid(t.id)} style={{display:"flex",alignItems:"center",gap:8,padding:"10px 14px",borderRadius:10,border:`1px solid ${a?`${t.acc}30`:T.bdr}`,background:a?`${t.acc}08`:"transparent",cursor:"pointer",minHeight:44}}><div style={{display:"flex",gap:3}}>{[t.bg,t.sf,t.tx,t.acc].map((c,i)=><div key={i} style={{width:12,height:12,borderRadius:"50%",background:c,border:"1px solid rgba(128,128,128,.12)"}}/>)}</div><span style={{fontFamily:T.ui,fontSize:12,fontWeight:a?700:500,color:a?t.acc:T.tx2}}>{t.name}</span></button>})}</div></Card>
<Card T={T} pad="16px" mb={14}><div style={{fontFamily:T.ui,fontSize:10,fontWeight:700,color:T.tx4,letterSpacing:".08em",textTransform:"uppercase",marginBottom:4}}>Notifications</div>{Object.entries(notifs).map(([k,v])=><Tog key={k} on={v} onToggle={()=>setN(p=>({...p,[k]:!p[k]}))} label={k.charAt(0).toUpperCase()+k.slice(1)}/>)}</Card>
<Card T={T} pad="16px" mb={14}><div style={{fontFamily:T.ui,fontSize:10,fontWeight:700,color:T.tx4,letterSpacing:".08em",textTransform:"uppercase",marginBottom:4}}>Privacy</div>{Object.entries(priv).map(([k,v])=><Tog key={k} on={v} onToggle={()=>setP(p=>({...p,[k]:!p[k]}))} label={k==="showReading"?"Show currently reading":k==="showLocation"?"Show on Reader Map":"Public profile"}/>)}</Card>
<Card T={T} pad="16px"><div style={{fontFamily:T.ui,fontSize:10,fontWeight:700,color:T.tx4,letterSpacing:".08em",textTransform:"uppercase",marginBottom:8}}>Data</div><div style={{display:"flex",flexDirection:"column",gap:8}}><button className="tb" style={{padding:"10px 14px",borderRadius:8,border:`1px solid ${T.bdr}`,background:"transparent",fontFamily:T.ui,fontSize:12,color:T.tx3,cursor:"pointer",textAlign:"left",minHeight:44}}>Import from Goodreads / StoryGraph</button><button className="tb" style={{padding:"10px 14px",borderRadius:8,border:`1px solid ${T.bdr}`,background:"transparent",fontFamily:T.ui,fontSize:12,color:T.tx3,cursor:"pointer",textAlign:"left",minHeight:44}}>Export my data</button><button className="tb" style={{padding:"10px 14px",borderRadius:8,border:`1px solid ${T.rd}15`,background:`${T.rd}04`,fontFamily:T.ui,fontSize:12,color:T.rd,cursor:"pointer",textAlign:"left",minHeight:44}}>Delete account</button></div></Card>
</Sec></div>;}

// ─── COMPOSE ─────────────────────────────────────────────────
function ComposeScreen({T,onClose,init}){
const[type,setType]=useState(init?.type||null);const[title,setTitle]=useState("");const[body,setBody]=useState("");const[bookRef,setBR]=useState(init?.bookRef||null);const[published,setPub]=useState(false);
const types=[{id:"original",label:"Original Work",desc:"Fiction, poetry, essays",icon:"✎"},{id:"review",label:"Review",desc:"Your take on a book",icon:"◈"},{id:"recommendation",label:"Recommendation",desc:"Share a must-read",icon:"⬨"},{id:"spoiler",label:"Spoiler Zone",desc:"Discuss freely with warnings",icon:"⚠"}];
if(published)return <div style={{animation:"en .3s ease both",textAlign:"center",padding:"60px 16px"}}><div style={{fontSize:48,marginBottom:16}}>✓</div><div style={{fontFamily:T.hd,fontSize:22,fontWeight:700,color:T.tx,marginBottom:8}}>Published!</div><div style={{fontFamily:T.bd,fontSize:13,color:T.tx3,marginBottom:20}}>Your post is live. +5 Ink earned.</div><button className="tb" onClick={onClose} style={{padding:"12px 24px",borderRadius:10,border:"none",background:T.acc,color:"#fff",fontFamily:T.ui,fontSize:13,fontWeight:700,cursor:"pointer",minHeight:44}}>Back to Feed</button></div>;
if(!type)return <div style={{animation:"en .3s ease both"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:20}}><h2 style={{fontFamily:T.hd,fontSize:22,fontWeight:700,color:T.tx}}>New Post</h2><button className="tb" onClick={onClose} style={{fontFamily:T.ui,fontSize:13,color:T.tx3,background:"none",border:"none",cursor:"pointer",minHeight:40}}>✕</button></div><div style={{display:"flex",flexDirection:"column",gap:10}}>{types.map(t=><button key={t.id} className="tb" onClick={()=>setType(t.id)} style={{display:"flex",alignItems:"center",gap:14,padding:"18px 16px",borderRadius:14,background:T.sf,border:`1px solid ${T.bdr}`,cursor:"pointer",textAlign:"left",minHeight:60}}><span style={{fontSize:24,width:40,textAlign:"center"}}>{t.icon}</span><div><div style={{fontFamily:T.ui,fontSize:14,fontWeight:700,color:T.tx}}>{t.label}</div><div style={{fontFamily:T.ui,fontSize:11,color:T.tx3}}>{t.desc}</div></div></button>)}</div></div>;
return <div style={{animation:"en .3s ease both"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:16}}><div style={{display:"flex",alignItems:"center",gap:8}}><button className="tb" onClick={()=>setType(null)} style={{fontFamily:T.ui,fontSize:12,color:T.tx3,background:"none",border:"none",cursor:"pointer",minHeight:40}}>← Back</button><TT T={T} type={type}/></div><button className="tb" onClick={()=>setPub(true)} disabled={!body.trim()} style={{padding:"8px 20px",borderRadius:8,border:"none",background:body.trim()?T.acc:`${T.tx4}20`,color:body.trim()?"#fff":T.tx4,fontFamily:T.ui,fontSize:12,fontWeight:700,cursor:body.trim()?"pointer":"default",minHeight:40}}>Publish</button></div>
{(type==="original"||type==="review"||type==="spoiler")&&<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Title…" style={{width:"100%",padding:"12px 0",borderRadius:0,background:"transparent",border:"none",borderBottom:`1px solid ${T.bdr}`,fontFamily:T.hd,fontSize:20,fontWeight:600,color:T.tx,outline:"none",marginBottom:12}}/>}
{bookRef&&<div style={{display:"flex",alignItems:"center",gap:10,padding:"10px 12px",borderRadius:8,background:T.bg2,border:`1px solid ${T.bdr}`,marginBottom:12}}><div style={{width:24,height:36,borderRadius:3,background:`linear-gradient(140deg,${T.acc}90,${T.acc}50)`,flexShrink:0}}/><div style={{flex:1,minWidth:0}}><div style={{fontFamily:T.ui,fontSize:12,fontWeight:600,color:T.tx}}>{bookRef.title}</div><div style={{fontFamily:T.ui,fontSize:10,color:T.tx3}}>{bookRef.author}</div></div><button className="tb" onClick={()=>setBR(null)} style={{background:"none",border:"none",fontSize:14,color:T.tx4,cursor:"pointer",minWidth:28,minHeight:28,display:"flex",alignItems:"center",justifyContent:"center"}}>✕</button></div>}
<textarea value={body} onChange={e=>setBody(e.target.value)} placeholder={type==="original"?"Start writing…":"Share your thoughts…"} rows={8} style={{width:"100%",padding:"12px 0",background:"transparent",border:"none",fontFamily:T.bd,fontSize:14.5,lineHeight:1.7,color:T.tx2,outline:"none",resize:"vertical",minHeight:200}}/>
<div style={{display:"flex",alignItems:"center",gap:12,marginTop:16,paddingTop:12,borderTop:`1px solid ${T.bdr}`}}><span style={{fontFamily:T.mn,fontSize:10,color:T.tx4}}>{body.split(/\s+/).filter(Boolean).length} words</span>{type==="original"&&<span style={{fontSize:8,padding:"2px 6px",borderRadius:3,background:`${T.gn}0D`,color:T.gn,fontFamily:T.ui,fontWeight:700}}>✓ These words are mine</span>}</div></div>;}

// ─── SEARCH MODAL ────────────────────────────────────────────
function SearchModal({T,feed,onClose,onCompose}){
const[q,setQ]=useState("");const[bks,setBks]=useState([]);const[bld,setBld]=useState(false);const[berr,setBerr]=useState(false);
const iRef=useRef(null);const tRef=useRef(null);
useEffect(()=>{
  if(tRef.current)clearTimeout(tRef.current);
  if(!q.trim()){setBks([]);setBld(false);return;}
  setBld(true);setBerr(false);
  tRef.current=setTimeout(()=>{
    fetch(`https://www.googleapis.com/books/v1/volumes?q=${encodeURIComponent(q)}&maxResults=6`)
      .then(r=>r.json()).then(d=>{setBks(d.items||[]);setBld(false);})
      .catch(()=>{setBerr(true);setBld(false);});
  },400);
  return()=>clearTimeout(tRef.current);
},[q]);
const psts=q.trim()?feed.filter(f=>{const lq=q.toLowerCase();return(f.title||"").toLowerCase().includes(lq)||(f.text||"").toLowerCase().includes(lq)||f.user.name.toLowerCase().includes(lq)||(f.bookRef?.title||"").toLowerCase().includes(lq);}):[];
useEffect(()=>{iRef.current?.focus();},[]);
return <div style={{position:"fixed",inset:0,zIndex:150,background:T.bg,overflowY:"auto",animation:"si .15s ease"}}>
<div style={{position:"sticky",top:0,background:`${T.bg}F2`,backdropFilter:"blur(20px)",borderBottom:`1px solid ${T.bdr}`,padding:"0 16px",height:52,display:"flex",alignItems:"center",gap:10,zIndex:10}}>
<button className="tb" onClick={onClose} style={{background:"none",border:"none",fontFamily:T.ui,fontSize:14,color:T.tx3,cursor:"pointer",minWidth:36,minHeight:36,display:"flex",alignItems:"center",justifyContent:"center"}}>←</button>
<div style={{flex:1,position:"relative"}}>
<input ref={iRef} value={q} onChange={e=>setQ(e.target.value)} placeholder="Search books or posts…" style={{width:"100%",padding:"10px 14px 10px 34px",borderRadius:10,background:T.bg2,border:`1px solid ${q?T.bdrA:T.bdr}`,fontFamily:T.ui,fontSize:14,color:T.tx,outline:"none"}}/>
<span style={{position:"absolute",left:11,top:"50%",transform:"translateY(-50%)",fontSize:15,color:T.tx4,pointerEvents:"none"}}>⌕</span>
{q&&<button className="tb" onClick={()=>setQ("")} style={{position:"absolute",right:10,top:"50%",transform:"translateY(-50%)",background:"none",border:"none",fontSize:14,color:T.tx4,cursor:"pointer",minWidth:28,minHeight:28,display:"flex",alignItems:"center",justifyContent:"center"}}>✕</button>}
</div>
</div>
<div style={{padding:"16px 14px",maxWidth:680,margin:"0 auto"}}>
{!q.trim()&&<div style={{textAlign:"center",padding:"48px 16px",color:T.tx4,fontFamily:T.bd,fontSize:14,fontStyle:"italic",animation:"fi .3s ease"}}>Search for books or posts on Précis…</div>}
{q.trim()&&<section style={{marginBottom:28}}>
<div style={{fontFamily:T.ui,fontSize:10,fontWeight:700,color:T.tx4,letterSpacing:".1em",textTransform:"uppercase",marginBottom:10}}>Books</div>
{bld&&<div style={{fontFamily:T.ui,fontSize:12,color:T.tx4,padding:"12px 0",display:"flex",alignItems:"center",gap:8}}><span style={{animation:"po 1s ease infinite"}}>⌕</span> Searching Google Books…</div>}
{berr&&<div style={{fontFamily:T.ui,fontSize:12,color:T.rd,padding:"12px 0"}}>Could not reach Google Books. Check connection.</div>}
{!bld&&!berr&&bks.length===0&&q.trim()&&<div style={{fontFamily:T.bd,fontSize:12,color:T.tx4,fontStyle:"italic",padding:"8px 0"}}>No books found.</div>}
{bks.map(b=>{const vi=b.volumeInfo||{};const thumb=vi.imageLinks?.thumbnail?.replace("http:","https:");const auth=(vi.authors||[]).join(", ");const amzUrl=`https://www.amazon.com/s?k=${encodeURIComponent((vi.title||"")+" "+(auth||""))}&tag=precis-20`;
return <div key={b.id} style={{display:"flex",alignItems:"flex-start",gap:12,padding:"14px 0",borderBottom:`1px solid ${T.bdr}`}}>
<div style={{width:42,height:60,borderRadius:3,flexShrink:0,background:`linear-gradient(140deg,${T.acc}90,${T.acc}50)`,overflow:"hidden"}}>{thumb&&<img src={thumb} alt="" style={{width:"100%",height:"100%",objectFit:"cover"}}/>}</div>
<div style={{flex:1,minWidth:0}}>
<div style={{fontFamily:T.hd,fontSize:15,fontWeight:600,color:T.tx,lineHeight:1.2,marginBottom:2}}>{vi.title||"Unknown"}</div>
<div style={{fontFamily:T.bd,fontSize:11,color:T.tx3,fontStyle:"italic",marginBottom:8}}>{auth||"Unknown author"}</div>
<div style={{display:"flex",gap:6,flexWrap:"wrap"}}>
<button className="tb" onClick={()=>onCompose({type:"review",bookRef:{title:vi.title||"",author:auth}})} style={{padding:"7px 12px",borderRadius:7,border:`1px solid ${T.gold}25`,background:`${T.gold}08`,fontFamily:T.ui,fontSize:11,fontWeight:700,color:T.gold,cursor:"pointer",minHeight:34}}>◈ Write Review</button>
<button className="tb" onClick={()=>onCompose({type:"recommendation",bookRef:{title:vi.title||"",author:auth}})} style={{padding:"7px 12px",borderRadius:7,border:`1px solid ${T.gn}25`,background:`${T.gn}08`,fontFamily:T.ui,fontSize:11,fontWeight:700,color:T.gn,cursor:"pointer",minHeight:34}}>⬨ Recommend</button>
<a href={amzUrl} target="_blank" rel="noopener noreferrer" style={{padding:"7px 12px",borderRadius:7,border:`1px solid ${T.bdr}`,fontFamily:T.ui,fontSize:11,fontWeight:600,color:T.tx3,textDecoration:"none",display:"inline-flex",alignItems:"center",minHeight:34}}>Amazon ↗</a>
</div>
</div>
</div>;})}
</section>}
{q.trim()&&<section>
<div style={{fontFamily:T.ui,fontSize:10,fontWeight:700,color:T.tx4,letterSpacing:".1em",textTransform:"uppercase",marginBottom:10}}>Posts · {psts.length} found</div>
{psts.length===0?<div style={{fontFamily:T.bd,fontSize:12,color:T.tx4,fontStyle:"italic",padding:"8px 0"}}>No posts match.</div>:<div style={{display:"flex",flexDirection:"column",gap:10}}>{psts.map((item,i)=><FC key={item.id} T={T} item={item} onToggle={()=>{}} index={i}/>)}</div>}
</section>}
</div>
</div>;}

// ─── THEME PICKER ────────────────────────────────────────────
function TP({T,tid,setTid}){const[open,setOpen]=useState(false);const ref=useRef(null);useEffect(()=>{if(!open)return;const h=e=>{if(ref.current&&!ref.current.contains(e.target))setOpen(false);};document.addEventListener("mousedown",h);document.addEventListener("touchstart",h);return()=>{document.removeEventListener("mousedown",h);document.removeEventListener("touchstart",h);};},[open]);
return <div ref={ref} style={{position:"relative"}}><button className="tb" onClick={()=>setOpen(!open)} style={{width:34,height:34,borderRadius:"50%",border:`1.5px solid ${T.bdr}`,background:T.bg2,cursor:"pointer",display:"flex",alignItems:"center",justifyContent:"center",fontSize:13}}>{THEMES[tid].icon}</button>{open&&<div style={{position:"absolute",top:"calc(100% + 8px)",right:0,background:T.sf,border:`1px solid ${T.bdrA}`,borderRadius:14,padding:6,minWidth:210,boxShadow:T.shL,zIndex:200,animation:"si .12s ease"}}><div style={{padding:"6px 12px 8px",fontFamily:T.ui,fontSize:9,fontWeight:700,color:T.tx4,letterSpacing:".08em",textTransform:"uppercase"}}>Reading Theme</div>{Object.values(THEMES).map(t=>{const a=t.id===tid;return <button key={t.id} className="tb" onClick={()=>{setTid(t.id);setOpen(false);}} style={{display:"flex",alignItems:"center",gap:10,padding:"10px 12px",borderRadius:10,border:"none",cursor:"pointer",width:"100%",minHeight:44,background:a?`${t.acc}0D`:"transparent"}}><div style={{display:"flex",gap:3}}>{[t.bg,t.sf,t.tx,t.acc,t.gold].map((c,i)=><div key={i} style={{width:10,height:10,borderRadius:"50%",background:c,border:"1px solid rgba(128,128,128,.12)"}}/>)}</div><span style={{fontFamily:T.ui,fontSize:12,fontWeight:a?700:500,color:a?t.acc:T.tx2}}>{t.name}</span>{a&&<span style={{marginLeft:"auto",fontSize:10,color:t.acc}}>✓</span>}</button>})}</div>}</div>;}

// ─── MAIN APP ────────────────────────────────────────────────
const TABS=[{id:"feed",label:"Feed",icon:"⊞"},{id:"explore",label:"Explore",icon:"◎"},{id:"press",label:"Press",icon:"✎"},{id:"compass",label:"Compass",icon:"⌖"},{id:"shelf",label:"Shelf",icon:"▤"}];

export default function PrecisApp(){
const{T,tid,setTid}=useTheme();const[tab,setTab]=useState("feed");const[feed,setFeed]=useState(FI);const[searchOpen,setSO]=useState(false);const[subView,setSV]=useState(null);const[composeInit,setCInit]=useState(null); // profile, messages, notifications, clubs, challenges, settings, compose, search

const onToggle=useCallback((id,type)=>{setFeed(prev=>prev.map(item=>{if(item.id!==id)return item;if(type==="like")return{...item,isLiked:!item.isLiked,likes:item.likes+(item.isLiked?-1:1)};if(type==="shelf")return{...item,isShelved:!item.isShelved,shelved:item.shelved+(item.isShelved?-1:1)};if(type==="repost")return{...item,isReposted:!item.isReposted,reposts:item.reposts+(item.isReposted?-1:1)};return item;}));},[]);
const unread=NOTIFS.filter(n=>!n.read).length;const msgUnread=CONVOS.reduce((a,c)=>a+c.unread,0);

function renderMain(){
if(subView==="search")return <SearchModal T={T} feed={feed} onClose={()=>setSV(null)} onCompose={(init)=>{setCInit(init);setSV("compose");}}/>;
if(subView==="compose")return <ComposeScreen T={T} init={composeInit} onClose={()=>{setSV(null);setCInit(null);}}/>;
if(subView==="profile")return <ProfileScreen T={T}/>;
if(subView==="messages")return <MessagesScreen T={T}/>;
if(subView==="notifications")return <NotifsScreen T={T}/>;
if(subView==="clubs")return <ClubsScreen T={T}/>;
if(subView==="challenges")return <ChallengesScreen T={T}/>;
if(subView==="settings")return <SettingsScreen T={T} tid={tid} setTid={setTid}/>;
if(tab==="feed")return <FeedScreen T={T} feed={feed} onToggle={onToggle} searchQ=""/>;
if(tab==="explore")return <ExploreScreen T={T}/>;
if(tab==="press")return <PressScreen T={T}/>;
if(tab==="compass")return <CompassScreen T={T}/>;
if(tab==="shelf")return <ShelfScreen T={T}/>;
return null;}

return <div style={{minHeight:"100vh",background:T.bg,color:T.tx,paddingBottom:72}}>
<style>{gc(T)}</style>

{/* MOBILE HEADER */}
<header className="mh" style={{position:"sticky",top:0,zIndex:100,background:`${T.bg}EC`,backdropFilter:"blur(20px) saturate(1.3)",borderBottom:`1px solid ${T.bdr}`,padding:"0 16px",height:52,display:"flex",alignItems:"center",gap:10}}>
{subView?<button className="tb" onClick={()=>setSV(null)} style={{fontFamily:T.ui,fontSize:14,color:T.tx3,background:"none",border:"none",cursor:"pointer",minWidth:36,minHeight:36}}>←</button>:<span style={{fontFamily:T.hd,fontSize:22,fontWeight:700,color:T.tx,letterSpacing:"-.02em",flexShrink:0}}>Pr<span style={{color:T.acc}}>é</span>cis</span>}
<div style={{flex:1}}/>
<button className="tb" onClick={()=>setSV("search")} style={{background:T.bg2,border:`1px solid ${T.bdr}`,borderRadius:10,fontSize:20,color:T.tx3,cursor:"pointer",padding:"0 10px",minWidth:44,minHeight:44,display:"flex",alignItems:"center",justifyContent:"center"}}>⌕</button>
<button className="tb" onClick={()=>setSV(sv=>sv==="notifications"?null:"notifications")} style={{background:"none",border:"none",fontSize:16,color:T.tx3,cursor:"pointer",padding:4,minWidth:36,minHeight:36,display:"flex",alignItems:"center",justifyContent:"center",position:"relative"}}>🔔{unread>0&&<div style={{position:"absolute",top:2,right:2,width:14,height:14,borderRadius:"50%",background:T.acc,fontFamily:T.ui,fontSize:8,fontWeight:700,color:"#fff",display:"flex",alignItems:"center",justifyContent:"center"}}>{unread}</div>}</button>
<button className="tb" onClick={()=>setSV(sv=>sv==="messages"?null:"messages")} style={{background:"none",border:"none",fontSize:16,color:T.tx3,cursor:"pointer",padding:4,minWidth:36,minHeight:36,display:"flex",alignItems:"center",justifyContent:"center",position:"relative"}}>✉{msgUnread>0&&<div style={{position:"absolute",top:2,right:2,width:14,height:14,borderRadius:"50%",background:T.acc,fontFamily:T.ui,fontSize:8,fontWeight:700,color:"#fff",display:"flex",alignItems:"center",justifyContent:"center"}}>{msgUnread}</div>}</button>
<button className="tb" onClick={()=>setSV(sv=>sv==="profile"?null:"profile")} style={{background:"none",border:"none",cursor:"pointer",padding:0}}><Av T={T} i={ME.in} ink={ME.ink} s={30}/></button>
</header>

{/* DESKTOP HEADER */}
<header className="dh" style={{display:"none",position:"sticky",top:0,zIndex:100,background:`${T.bg}E8`,backdropFilter:"blur(20px) saturate(1.3)",borderBottom:`1px solid ${T.bdr}`}}>
<div style={{maxWidth:1040,margin:"0 auto",padding:"0 28px",height:56,display:"flex",alignItems:"center"}}>
<span style={{fontFamily:T.hd,fontSize:24,fontWeight:700,color:T.tx,letterSpacing:"-.02em",marginRight:32,flexShrink:0,cursor:"pointer"}} onClick={()=>{setTab("feed");setSV(null);}}>Pr<span style={{color:T.acc}}>é</span>cis</span>
<div style={{display:"flex",gap:1}}>{TABS.map(n=><button key={n.id} className="tb" onClick={()=>{setTab(n.id);setSV(null);}} style={{padding:"8px 14px",borderRadius:8,border:"none",fontFamily:T.ui,fontSize:12.5,fontWeight:tab===n.id&&!subView?700:500,cursor:"pointer",background:tab===n.id&&!subView?T.gs:"transparent",color:tab===n.id&&!subView?T.gold:T.tx3,display:"flex",alignItems:"center",gap:5}}><span style={{fontSize:14}}>{n.icon}</span> {n.label}</button>)}</div>
<div style={{display:"flex",gap:1,marginLeft:8}}>{[{id:"clubs",l:"Clubs"},{id:"challenges",l:"Challenges"}].map(n=><button key={n.id} className="tb" onClick={()=>setSV(n.id)} style={{padding:"8px 12px",borderRadius:8,border:"none",fontFamily:T.ui,fontSize:12,fontWeight:subView===n.id?700:500,cursor:"pointer",background:subView===n.id?T.gs:"transparent",color:subView===n.id?T.gold:T.tx4}}>{n.l}</button>)}</div>
<div className="tb" onClick={()=>setSV("search")} style={{flex:1,maxWidth:240,margin:"0 20px",position:"relative",cursor:"pointer"}}><div style={{width:"100%",padding:"8px 14px 8px 32px",borderRadius:8,background:T.bg3,border:`1px solid ${T.bdr}`,fontFamily:T.ui,fontSize:12,color:T.tx4,userSelect:"none",minHeight:34,display:"flex",alignItems:"center"}}>Search books &amp; posts…</div><span style={{position:"absolute",left:11,top:"50%",transform:"translateY(-50%)",fontSize:13,color:T.tx4,pointerEvents:"none"}}>⌕</span></div>
<div style={{flex:1}}/>
<button className="tb" onClick={()=>setSV("compose")} style={{padding:"8px 20px",borderRadius:8,border:"none",background:T.acc,color:"#fff",fontFamily:T.ui,fontSize:12,fontWeight:700,cursor:"pointer",boxShadow:`0 2px 8px ${T.acc}30`,display:"flex",alignItems:"center",gap:5,marginRight:10}}>✎ Write</button>
<button className="tb" onClick={()=>setSV(sv=>sv==="notifications"?null:"notifications")} style={{background:"none",border:"none",fontSize:16,color:T.tx3,cursor:"pointer",padding:6,position:"relative"}}>🔔{unread>0&&<div style={{position:"absolute",top:0,right:0,width:14,height:14,borderRadius:"50%",background:T.acc,fontFamily:T.ui,fontSize:8,fontWeight:700,color:"#fff",display:"flex",alignItems:"center",justifyContent:"center"}}>{unread}</div>}</button>
<button className="tb" onClick={()=>setSV(sv=>sv==="messages"?null:"messages")} style={{background:"none",border:"none",fontSize:16,color:T.tx3,cursor:"pointer",padding:6,marginRight:8,position:"relative"}}>✉{msgUnread>0&&<div style={{position:"absolute",top:0,right:0,width:14,height:14,borderRadius:"50%",background:T.acc,fontFamily:T.ui,fontSize:8,fontWeight:700,color:"#fff",display:"flex",alignItems:"center",justifyContent:"center"}}>{msgUnread}</div>}</button>
<TP T={T} tid={tid} setTid={setTid}/>
<button className="tb" onClick={()=>setSV(sv=>sv==="profile"?null:"profile")} style={{display:"flex",alignItems:"center",gap:8,marginLeft:8,cursor:"pointer",background:"none",border:"none"}}><Av T={T} i={ME.in} ink={ME.ink} s={32}/><div style={{lineHeight:1.2,textAlign:"left"}}><div style={{fontFamily:T.ui,fontSize:12,fontWeight:600,color:T.tx}}>{ME.name}</div><IB T={T} ink={ME.ink} compact/></div></button>
</div></header>

{/* CONTENT */}
<div style={{padding:"16px 14px 0"}} className="fw"><div className={tab==="feed"&&!subView?"fs":""}><main>{renderMain()}</main>
{tab==="feed"&&!subView&&<aside className="sd" style={{display:"none",flexDirection:"column",gap:14,position:"sticky",top:76,animation:"en .4s ease .1s both"}}>
<Card T={T} pad="16px 16px 8px"><div style={{fontFamily:T.hd,fontSize:16,fontWeight:600,color:T.tx,marginBottom:12}}>Trending Now</div>{TRD.map((b,i)=><div key={i} style={{display:"flex",alignItems:"center",gap:10,padding:"10px 4px",borderBottom:i<TRD.length-1?`1px solid ${T.bdr}`:"none",minHeight:48}}><div style={{fontFamily:T.mn,fontSize:11,fontWeight:500,color:T.tx4,width:18,textAlign:"center"}}>{i+1}</div><div style={{width:22,height:32,borderRadius:3,flexShrink:0,background:`linear-gradient(140deg,${b.c}AA,${b.c}60)`}}/><div style={{flex:1,minWidth:0}}><div style={{fontFamily:T.ui,fontSize:12,fontWeight:600,color:T.tx}}>{b.title}</div><div style={{fontFamily:T.ui,fontSize:10,color:T.tx3}}>{b.author}</div></div><span style={{fontFamily:T.mn,fontSize:10,fontWeight:500,color:T.gn,background:`${T.gn}0D`,padding:"2px 6px",borderRadius:3}}>{b.heat}</span></div>)}</Card>
<Card T={T} pad="16px 16px 8px"><div style={{fontFamily:T.hd,fontSize:16,fontWeight:600,color:T.tx,marginBottom:12}}>Ink Leaders</div>{[...US].sort((a,b)=>b.ink-a.ink).slice(0,5).map((u,i)=><div key={u.id} style={{display:"flex",alignItems:"center",gap:8,padding:"8px 2px",borderBottom:i<4?`1px solid ${T.bdr}`:"none"}}><div style={{fontFamily:T.mn,fontSize:11,fontWeight:500,color:i<3?T.gold:T.tx4,width:16}}>{i+1}</div><Av T={T} i={u.in} ink={u.ink} s={26}/><div style={{flex:1,fontFamily:T.ui,fontSize:11.5,fontWeight:600,color:T.tx}}>{u.name}</div><span style={{fontFamily:T.mn,fontSize:10,fontWeight:500,color:gT(u.ink).c}}>{fN(u.ink)}</span></div>)}</Card>
<div style={{padding:"10px 0",fontFamily:T.ui,fontSize:10,color:T.tx4,lineHeight:1.8}}><div style={{display:"flex",gap:12,flexWrap:"wrap",marginBottom:4}}>{["About","TOS","Privacy"].map(l=><span key={l} style={{cursor:"pointer"}}>{l}</span>)}</div>© 2026 Précis Technologies, Inc.</div>
</aside>}</div></div>

{/* MOBILE BOTTOM BAR */}
<nav className="bb" style={{position:"fixed",bottom:0,left:0,right:0,zIndex:100,background:`${T.bg}F2`,backdropFilter:"blur(20px) saturate(1.3)",borderTop:`1px solid ${T.bdr}`,display:"flex",alignItems:"stretch",height:60,paddingBottom:"env(safe-area-inset-bottom,0px)"}}>
{TABS.map(t=>{const a=tab===t.id&&!subView;return <button key={t.id} className="tb" onClick={()=>{setTab(t.id);setSV(null);}} style={{flex:1,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",gap:2,background:"none",border:"none",cursor:"pointer",color:a?T.gold:T.tx4,minHeight:48,position:"relative"}}>{a&&<div style={{position:"absolute",top:0,left:"50%",transform:"translateX(-50%)",width:20,height:2,borderRadius:1,background:T.gold}}/>}<span style={{fontSize:20,lineHeight:1}}>{t.icon}</span><span style={{fontFamily:T.ui,fontSize:9,fontWeight:a?700:500}}>{t.label}</span></button>})}
<div onClick={()=>setSV("compose")} style={{position:"absolute",top:-22,left:"50%",transform:"translateX(-50%)",width:48,height:48,borderRadius:"50%",background:`linear-gradient(135deg,${T.acc},#9A4520)`,boxShadow:`0 4px 16px ${T.acc}50`,display:"flex",alignItems:"center",justifyContent:"center",cursor:"pointer",zIndex:10}}><span style={{fontSize:20,color:"#fff",marginTop:-1}}>✎</span></div>
{/* More menu items */}
<button className="tb" onClick={()=>setSV(sv=>sv==="settings"?null:"settings")} style={{position:"absolute",right:8,top:-32,width:32,height:32,borderRadius:"50%",background:T.bg2,border:`1px solid ${T.bdr}`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:14,color:T.tx4,cursor:"pointer"}}>⚙</button>
</nav>
</div>;}
